### ISSUE TITLE
Console Interview

### ISSUE THREAD

**Issue by sjkelleyjr** [m1k1o/neko#110]
Hey Miroslav!

I run [a newsletter about open source software](https://console.substack.com/) and I like to put an interview with one of the developers in each email.  Would you be interested in answering a few questions about software development and Neko?

If so, you can send me an email at console . substack @ gmail . com, or just respond to this thread 😀

**Comment by m1k1o** [comment]
Hey, sure. You can also join discord group, invite link is in readme. And maybe it would be interesting to include original author @nurdism, who created this project originally.

**Comment by nurdism** [comment]
@sjkelleyjr just DM me on discord any questions you have 👍🏻
