### ISSUE TITLE
[Bug] Control icon hidden for some screen sizes.

### ISSUE THREAD

**Issue by akashsharma95** [m1k1o/neko#112]
There is probably some issue with how control icon placement is handled in UI.

- Control icon not visible
![Screenshot_20211208-023742__01.jpg](https://user-images.githubusercontent.com/1501547/145107088-9693cd3e-269f-4e9e-9d11-52e26aa063e4.jpg)

- Control icon visible
![Screenshot_20211208-023624.jpg](https://user-images.githubusercontent.com/1501547/145107224-80424e29-4cd0-416c-add4-8adf34994d57.jpg)

Screenshot is of Chrome Browser running on Android.

**Comment by m1k1o** [comment]
Interesting, on desktop it does not happen:
![image](https://user-images.githubusercontent.com/7534274/145111634-345ffefb-b71e-4010-b91f-bcb73305a375.png)

It looks like your mobile is wide enough to show desktop GUI, but that button is hidden for touchscreens. This control change must be unified and not dependent on screen size and touch screen.
