### ISSUE TITLE
[Question] Hardware accellaration using a video card? 

### ISSUE THREAD

**Issue by Catsrules** [m1k1o/neko#119]
I haven't seen any information on this, but it is possible to pass a video card to Neko? So it could be less CPU intensive and be able to encode higher resolution and bitrates? From my understanding videos cards can encode and handle video streaming better then a CPU can. 
I know many people running Plex or Jellyfin servers will pass a video card to those services so it handles the video transcoding. 

I was just wondering if Neko could benefit from this solution as well. 

Thanks.

**Comment by m1k1o** [comment]
There have been some attempts to accelerate video encoding using GPU, for Raspberry Pi it has been succesfull. But passing GPU to the environment and have browser using it, is much harder. So this topic is stil open.

**Comment by Catsrules** [comment]
Ahh thanks for the quick response. I was just curious if buying a video card or finding a new server with quick sync support for my local Neko server would help at all. Sounds like it might help in the furniture but not at the moment. 

Thanks.

**Comment by lowne** [comment]
> pass a video card to those services so it handles the video transcoding

>  finding a new server with quick sync support for my local Neko server would help at all

@Catsrules it's indeed implemented for Intel QSV since #151 - see instructions in the top comment 

> have browser using it, is much harder

I've been trying to convince Firefox to *also* use QuickSync for *decoding* (e..g YouTube) but I've been unsuccessful so far; it'd probably be easier with Chromium but haven't tried that yet.

**Comment by Catsrules** [comment]
Excellent, this is a huge feature add to Neko. Right now I just bought bigger CPUs with more cores. But Intel Quick Sync will but much more energy efficient for live video encoding. 

Thanks for you hard work on this project it has been extremely handy program. :)
