### ISSUE TITLE
no element "v4l2h264enc" error in arm-* containers

### ISSUE THREAD

**Issue by DX37** [m1k1o/neko#128]
Hello there.

I'm using `arm-chromium` container and Raspberry Pi example docker-compose config. Today I encountered error, which I don't understand why happens. It appears neko or gstreamer can't find v4l2h264enc element or even omxh264enc element, which I tried to use myself.
I exec'ed with shell into container and I think gst packages installed properly, but it's still doesn't work.
I tried to build containers with `build` script, but it didn't help.

There's [log.txt](https://github.com/m1k1o/neko/files/7859585/log.txt) from container.

**Comment by DX37** [comment]
Trying to rebuild these containers, starting with `arm-base`. Excuse me, forgot to rebuild it.

**Comment by m1k1o** [comment]
Did that fix issue? `arm-` images are not built automatically, as #102 is not resolved yet. They can be outdated. And also make sure, you did not forget `--privileged: true` and you don't have installed docker in [rootless mode](https://docs.docker.com/engine/security/rootless/).

**Comment by DX37** [comment]
> Did that fix issue? `arm-` images are not built automatically, as #102 is not resolved yet. They can be outdated. And also make sure, you did not forget `--privileged: true` and you don't have installed docker in [rootless mode](https://docs.docker.com/engine/security/rootless/).

No, it didn't. Same issue.
Docker runs as service under root, and I starting built containers with docker-compose config for Raspberry Pi, which have this `privileged` option.
What else I can do?

**Comment by m1k1o** [comment]
I just took Raspberry Pi 3 Model B+, built arm images and started using unchanged example configuration. It works out of the box, did not find any problems on the way.

Can you chek if you have working [kernel side support](https://stackoverflow.com/questions/64426904/no-such-element-or-plugin-v4l2h264enc)? Do you use Raspberry Pi 4?

A more detailed Thread about similar issue and related errors can be found here:
https://forums.raspberrypi.com/viewtopic.php?f=38&t=269590&p=1646533#p1646533

**Comment by yesBad** [comment]
I can test my Raspberry Pi 4 (4GB) tomorrow if it works 🙃

**Comment by DX37** [comment]
> Can you chek if you have working kernel side support? Do you use Raspberry Pi 4?

Yes, I can. Because I have Raspberry Pi 4 too  and I wouldn't create issue if I didn't have one.

And yes, I have kernel side support, out of the box:
```
root@raspi4 /opt/neko # v4l2-ctl -D -d 11                                                       Driver Info:                                                                                            Driver name      : bcm2835-codec                                                                Card type        : bcm2835-codec-encode                                                         Bus info         : platform:bcm2835-codec                                                       Driver version   : 5.10.90                                                                      Capabilities     : 0x84204000                                                                           Video Memory-to-Memory Multiplanar                                                              Streaming                                                                                       Extended Pix Format                                                                             Device Capabilities
        Device Caps      : 0x04204000                                                                           Video Memory-to-Memory Multiplanar
                Streaming                                                                                       Extended Pix Format                                                             Media Driver Info:                                                                                      Driver name      : bcm2835-codec                                                                Model            : bcm2835-codec                                                                Serial           : 0000                                                                         Bus info         : platform:bcm2835-codec                                                       Media version    : 5.10.90                                                                      Hardware revision: 0x00000001 (1)                                                               Driver version   : 5.10.90                                                              Interface Info:                                                                                         ID               : 0x0300001a                                                                   Type             : V4L Video                                                            Entity Info:                                                                                            ID               : 0x0000000f (15)                                                              Name             : bcm2835-codec-encode-source
        Function         : V4L2 I/O                                                                     Pad 0x01000010   : 0: Source                                                                      Link 0x02000016: to remote pad 0x1000012 of entity 'bcm2835-codec-encode-proc' (Video Encoder): Data, Enabled, Immutable
```

**Comment by m1k1o** [comment]
@DX37 could you please try with latest arm images?

https://neko.m1k1o.net/#/getting-started/
![image](https://user-images.githubusercontent.com/7534274/229381215-69346e6a-5809-466f-b3cf-5efb5dd0c557.png)

**Comment by DX37** [comment]
> @DX37 could you please try with latest arm images?
> 
> https://neko.m1k1o.net/#/getting-started/ ![image](https://user-images.githubusercontent.com/7534274/229381215-69346e6a-5809-466f-b3cf-5efb5dd0c557.png)

Unfortunately I can't - switched to x86 server last summer ¯\_(⌐■_■)_/¯
