### ISSUE TITLE
How to turn on chat sound permanently?

### ISSUE THREAD

**Issue by reformedp** [m1k1o/neko#131]
I am using neko:latest docker image. I would like to have chat sound on whenever a user first connects and reconnects. Currently, the chat sound is off when I login. After I turn on the chat sound, upon refreshing, the chat sound is reset to off.

I have tried my hand at this problem, and I saw the various settings in settings.ts file, but I don't know how to change it for the docker image.

Thank you.

**Comment by yesBad** [comment]
You have to edit the source-code and build the docker image.

Building instructions can be found [here](https://github.com/m1k1o/neko/tree/master/.docker)

**Comment by reformedp** [comment]
Just to clarify, other items in settings such as "Scroll Sensitivity", "Invert Scroll", "Ignore Emotes" are able to persist between refreshes. Only "Play Chat Sound" does not persist. I am using firefox, if that matters.

Also, in settings.ts line 18, chat sound already seems to be initialised to true.

I am not too sure how to approach this issue.

**Comment by yesBad** [comment]
> Just to clarify, other items in settings such as "Scroll Sensitivity", "Invert Scroll", "Ignore Emotes" are able to persist between refreshes. Only "Play Chat Sound" does not persist. I am using firefox, if that matters.
> 
> Also, in settings.ts line 18, chat sound already seems to be initialised to true.
> 
> I am not too sure how to approach this issue.

Oh I didn't even realize that they persisted, that's interesting that it exactly doesn't persist.
But you could just simply modify the docker image in the line 18 of the settings.ts file you found and then rebuild the docker image and be good to go

**Comment by reformedp** [comment]
Thanks for pointing out how to modify the docker image. I have found the line to modify: it is app.vue line 186. Seems like hideControls is activated when loading the page.

**Comment by m1k1o** [comment]
Seems like a bug, I'll take a look at it.

**Comment by m1k1o** [comment]
It should be fixed now, _Play Chat Sound_ is again persistent as all other settings.

**Comment by reformedp** [comment]
Thank you, the issue is fixed.
