### ISSUE TITLE
Couldn't download a rar file

### ISSUE THREAD

**Issue by nawkht** [m1k1o/neko#139]
Hi, I'm trying to use Neko to reupload some files
I tweaked some settings in policies.json 
Screenshot : https://prnt.sc/26leo03

Code :

`{
  "HomepageLocation": "",
  "AutoFillEnabled": false,
  "AutofillAddressEnabled": false,
  "AutofillCreditCardEnabled": false,
  "BrowserSignin": 0,
  "DefaultNotificationsSetting": 2,
  "DeveloperToolsAvailability": 1,
  "EditBookmarksEnabled": false,
  "FullscreenAllowed": true,
  "IncognitoModeAvailability": 1,
  "SyncDisabled": true,
  "AutoplayAllowed": true,
  "BrowserAddPersonEnabled": false,
  "BrowserGuestModeEnabled": false,
  "DefaultPopupsSetting": 2,
  "DownloadRestrictions": 0,
  "VideoCaptureAllowed": true,
  "AllowFileSelectionDialogs": true,
  "PromptForDownloadLocation": false,
  "BookmarkBarEnabled": false,
  "PasswordManagerEnabled": false,
  "URLBlacklist": [],
  "ExtensionInstallForcelist": [
      "cjpalhdlnbpafiamejdnhcphjbkeiagm;https://clients2.google.com/service/update2/crx",
      "eimadpbcbfnmbkopoojfekhnkhdbieeh;https://clients2.google.com/service/update2/crx",
      "ldgfbffkinooeloadekpmfoklnobpien;https://clients2.google.com/service/update2/crx",
      "goeclnlkhfoejbhdebemhjljlmcbhfkp;https://clients2.google.com/service/update2/crx",
      "eppiocemhmnlbhjplcgkofciiegomcon;https://clients2.google.com/service/update2/crx",
      "eppiocemhmnlbhjplcgkofciiegomcon;https://clients2.google.com/service/update2/crx",
      "nngceckbapebfimnlniiiahkandclblb;https://clients2.google.com/service/update2/crx",
  ],
  "ExtensionInstallWhitelist": [
      "nngceckbapebfimnlniiiahkandclblb"
  ],
  "ExtensionInstallBlacklist": [
      "*"
  ]
}
`

I can download PDFs / Images , but I can't download RAR files as an example is stays like this:
https://prnt.sc/26lemu8

Also do you think there is a way to exctarct rar / zip files within Neko ? 
I found a chrome extension, I'm not sure if that's the best way 
https://chrome.google.com/webstore/detail/unrar-and-rar-viewer/goeclnlkhfoejbhdebemhjljlmcbhfkp

Thanks.

**Comment by m1k1o** [comment]
I see you have correctly set `"DownloadRestrictions": 0,` and `"AllowFileSelectionDialogs": false`, apart from that I don't know about any limitation that would deny explicitly rar files.

You could use `xfce` image and install software for extracting files, like 7zip.

**Comment by nawkht** [comment]
I was setting `AllowFileSelectionDialogs` to `true` in my screenshot, tried changing it to false but still couldn't manage to make it work.
Btw I'm using an arm processor, I guess Xfce is not a solution for me right?

**Comment by m1k1o** [comment]
There is not explicitly provided arm dockerfile for that, but the existing one migt support it. You can try [to build it by yourself](https://github.com/m1k1o/neko/tree/master/.docker) and see if it works.

**Comment by m1k1o** [comment]
Closing as this issue is stale and most likely problem with browser itself not neko.
