### ISSUE TITLE
Chromium not loading widevine component

### ISSUE THREAD

**Issue by AbanoubNassem** [m1k1o/neko#141]
I can tell that , the `widevine` being downloaded and copied to `Chromium`:

`DockerFile`
```
    # install widevine module
    WIDEVINE_VERSION=$(wget --quiet -O - https://dl.google.com/widevine-cdm/versions.txt | tail -n 1); \
    wget -O /tmp/widevine.zip "https://dl.google.com/widevine-cdm/$WIDEVINE_VERSION-linux-x64.zip"; \
    unzip -p /tmp/widevine.zip libwidevinecdm.so > /usr/lib/chromium/libwidevinecdm.so; \
    chmod 644 /usr/lib/chromium/libwidevinecdm.so; \
    rm /tmp/widevine.zip; \
```

however it's not being loaded into the browser , by going to `chrome://components/` it's not presented there, any clue what is the cause of this issue?

**Comment by m1k1o** [comment]
Do you maybe have arm arch? https://github.com/m1k1o/neko/issues/93#issuecomment-932896647

**Comment by AbanoubNassem** [comment]
> Do you maybe have arm arch? [#93 (comment)](https://github.com/m1k1o/neko/issues/93#issuecomment-932896647)

nope it's x86_64: 
```
root@m606:~# uname -m
x86_64
```

**Comment by m1k1o** [comment]
I can reporduce it, maybe there have been changes in latest chromium versions. In Google Chrome & Firefox should DRM work.

**Comment by AbanoubNassem** [comment]
> I can reporduce it, maybe there have been changes in latest chromium versions. In Google Chrome & Firefox should DRM work.

Google Chrome , shows black screen , just the cursor , I have tried to use downgraded versions , 96.0.4664.45,93.0.4577.82-1 etc , and all result with the same thing !? 

should I open different issue for that?

**Comment by m1k1o** [comment]
Might be related to https://github.com/m1k1o/neko/issues/134

**Comment by AbanoubNassem** [comment]
> Might be related to #134

yes it is actually , downgrading , isn't solving it.

**Comment by m1k1o** [comment]
![image](https://user-images.githubusercontent.com/7534274/155885226-1995705a-a597-4864-ab2e-9182fbd06f85.png)

In the lastest comit.
