### ISSUE TITLE
Why is the Nordvpn addon included?

### ISSUE THREAD

**Issue by e00E** [m1k1o/neko#143]
This is a random third party vpn vendor's extensions which requires extensive permissions "read and change your data on all sites". Why is it included by default?

**Comment by m1k1o** [comment]
I don't know, that decision pre-dates this fork, it has been included in [this commit](https://github.com/nurdism/neko/commit/56464778f2568b8f96e82ce258b7fc63ccf2a80f#diff-a00655ca026d10a4e140ccd55f00a1dfde00a78455d8ee29b2bc716aa65c125fR122-R125). And there is another request for an extension: https://github.com/m1k1o/neko/issues/83.

**Comment by e00E** [comment]
Thanks for finding the original commit. Since there is reason for the addon to be included I feel it should it be removed.
I don't feel that way about ublock origin and sponsor block because those extensions are open source and have a clear benefit to users for the common use case of this project.

**Comment by m1k1o** [comment]
I agree with you, in that case, Nordvpn should be replaced with sponsor block.
