### ISSUE TITLE
Disable Login/Password?

### ISSUE THREAD

**Issue by liorsbg** [m1k1o/neko#145]
Hi, thanks for this amazing project!
Is there a way to allow access without login? Any help (i.e. where to look in the code) would be appreciated.
Ideally, I'm trying to create the most minimal experience possible: Go to a URL and see a full screen browser.

Thanks!

**Comment by mbattista** [comment]
Hi,

both is already possible. But the documentation has the features hidden in the changelog.

```
Added ?usr=<display-name> that will prefill username. This allows creating auto-join links.
Added ?cast=1 that will hide all control and show only video.
```

`http(s)://<URL:Port>/?usr=guest&cast=1` should do exactly what you want.

**Comment by liorsbg** [comment]
Perfect, thank you!
