### ISSUE TITLE
is it possible to stream to a large audience?

### ISSUE THREAD

**Issue by dragonballa** [m1k1o/neko#149]
it seems that this is not SFU and so it can at best support 10 peers? or am I mistaken?

is it possible to stream video/audio to a larger audience like 100?

**Comment by yesBad** [comment]
From what I understand, you can stream to infinite*, if your server just have the specs / internet for it.

**Comment by m1k1o** [comment]
SFU is meant to route communication between users. It makes sense, if the number of track per users would be proportional to number of connected users (e.g. webcam streams for conference apps). Every connected user has 3 tracks (two downstream for audio, video and one upstream for cursor events) regardless of how many people are connected to it.

Of course, SFU can also provide specific stream quality and codec to the client depending on bandwidth and support, what ist not implemented here yet. So as @yesBad said, it only depends on your server's resources and network connection.

**Comment by mbattista** [comment]
> it seems that this is not SFU

It is basically SFU. Based on Pion WebRTC https://github.com/pion/webrtc. Pion has be used for WebRTC solutions with larger audiences, e.g. galene ( https://github.com/jech/galene ).

With a video bitrate setting of 2000 kb/s you would need at least an upload of 250mb/s for an audience of 100 people.
I cannot say anything about the CPU requirements for a stream that size.

**Comment by dragonballa** [comment]
> > it seems that this is not SFU
> 
> It is basically SFU. Based on Pion WebRTC https://github.com/pion/webrtc. Pion has be used for WebRTC solutions with larger audiences, e.g. galene ( https://github.com/jech/galene ).
> 
> With a video bitrate setting of 2000 kb/s you would need at least an upload of 250mb/s for an audience of 100 people. I cannot say anything about the CPU requirements for a stream that size.

ah I see. I was thinking it was like Twitch where instead of relying on your own upstream limits from ISP, you use the VPS capacity. 

thanks guys!

**Comment by mbattista** [comment]
> ah I see. I was thinking it was like Twitch where instead of relying on your own upstream limits from ISP, you use the VPS capacity.
> 
> thanks guys!

Well you can host neko on AWS, Hetzner, azure or any other cloud/vps provider in which case your private upload is not needed at all.

**Comment by m1k1o** [comment]
> instead of relying on your own upstream limits from ISP, you use the VPS capacity

There has been question about it https://github.com/m1k1o/neko/issues/135, but as @mbattista said, _you can host neko on AWS, Hetzner, azure or any other cloud/vps provider_, it makes no sense to split those application parts. It would just increase latency.
