### ISSUE TITLE
support for voice chat?

### ISSUE THREAD

**Issue by dragonballa** [m1k1o/neko#150]
are there any plans for voice chat in rooms?

**Comment by yesBad** [comment]
Nope there are not. Its a non-goal for n.eko.

**Comment by m1k1o** [comment]
You can create own client that implements voice chat and import neko. We do provide bindings for that.
https://github.com/m1k1o/neko/blob/ba3368a3eb6bad6287ee1a4b908b4921dc3099df/client/src/lib.ts
