### ISSUE TITLE
firefox image: openbox window controls visible.

### ISSUE THREAD

**Issue by ranomier** [m1k1o/neko#152]
With the firefox image the openbox config is broken.

- Because per default the app isn't maximized, if you change the resolution, you can't see all of firefox.
- If you minimize it there is now way of bringing it back

Thank you for your work :3 :+1:

**Comment by m1k1o** [comment]
@ranomier should be fixed on master, can you confirm?

**Comment by gbrian** [comment]
@m1k1o Issue is gone after pulling latest m1k1o/neko:firefox 👏 Thanks!

**Comment by ranomier** [comment]
Yes i can confirm to ;)

Thank you! :+1:
