### ISSUE TITLE
Firefox context menu appears on top of app/web context menu

### ISSUE THREAD

**Issue by gbrian** [m1k1o/neko#160]
Hi,

When using web apps inside neko, the firefox's context menu is shown shadowing the app's context menu

<img width="432" alt="image" src="https://user-images.githubusercontent.com/767180/160061843-fdd55e2a-3f8e-4ef2-bd3d-ebfc93319d78.png">

Have you experienced this behavior?

**Comment by gbrian** [comment]
Answering myself: https://support.mozilla.org/en-US/questions/1022204

https://github.com/m1k1o/neko/blob/2189e4fd4990369092a4ac2367d48054a5cc940c/.docker/firefox/policies.json#L111 

So any concerns on changing that @m1k1o ?

**Comment by m1k1o** [comment]
Looks good, i think it could be changed here in default config.
