### ISSUE TITLE
Neko with owncast

### ISSUE THREAD

**Issue by haliliceylan** [m1k1o/neko#165]
Hi guys, i am trying use neko rtmp stream feature with owncast but its not working.

Is there any guess why is this not working ?

**Comment by mbattista** [comment]
Hi,

with this little input we cannot help you at all.

Can you further elaborate what you are doing and where it is not working.

E.g. did you start neko with the rtmp parameters set as docker env variables or do you set them later over the frontend?
Can you ping your owncast server from the neko server?
Are any errors thrown in neko or owncast?

**Comment by haliliceylan** [comment]
thank you very much for you answer, i will be add more information asap.

**Comment by Technetium1** [comment]
@haliliceylan If this is solved, can you post what was wrong and what the solution was.
