### ISSUE TITLE
Microphone support?

### ISSUE THREAD

**Issue by justinlu** [m1k1o/neko#169]
Does neko have microphone support? I didn't see a microphone/recording device available in chrome. So voice search or voice recording are available in browser.

It would be great the microphone can be supported. :-)

**Comment by yesBad** [comment]
I don't get it. You want voice chat or wdym?

**Comment by justinlu** [comment]
Yes, voice chat & meeting. Or just voice search, see Google or YouTube.

**Comment by yesBad** [comment]
![chrome_WhTcJTfQKS](https://user-images.githubusercontent.com/87938689/162883395-8b4fd760-1e82-4ca7-aa49-56ea5d842cb7.png)

**Comment by justinlu** [comment]
Right, microphone support for remote browser. I would like to use voice search and other voice functions in remote Chrome browser.

In Chrome container "m1k1o/neko:chromium", it seems that the local microphone is not mapped to the remote browser. So all voice functions in remote browser don't work.

**Comment by yesBad** [comment]
Ngl,  I didn't know people even use voice search.

**Comment by m1k1o** [comment]
Adding external peripherals is not planned as of now.
