### ISSUE TITLE
Missing fonts cause many unicode characters to not render correctly

### ISSUE THREAD

**Issue by Apt1tude** [m1k1o/neko#179]
The docker images for Neko seems to be missing support for a lot of unicode characters, causing Chinese/Japanese to not render correctly. Can we have the `fonts-wqy-zenhei` package added to the base image (I can open a PR assuming this is something we want to do)? It provides fairly comprehensive support for Asian languages and would greatly improve i18n.

**Comment by m1k1o** [comment]
We already added `fonts-takao-mincho` in https://github.com/m1k1o/neko/commit/4d4485ab6d765905f71facf1317c408fe62d882f hoping that support for Asian languages would improve. But we can add this as well.
