### ISSUE TITLE
request dockerfile

### ISSUE THREAD

**Issue by herokuhint** [m1k1o/neko#180]
Hi Miroslav,
please make dockerfile at root of project for easily deploy on cloud containers.
waiting for your commit/s.
finest regards

**Comment by m1k1o** [comment]
Hello, we have [multiple options](https://neko.m1k1o.net/#/getting-started/?id=getting-started-amp-faq) for different browsers and programs, therefore it cannot be joined to only one Dockerfile.

Furthermore, this separation is done in two steps. First, we build base image that contains shared code for every image. On top of that is just added desired program such as browser.

For build instructions visit [.docker](https://github.com/m1k1o/neko/tree/master/.docker) folder.
