### ISSUE TITLE
The arm-base cannot render Japanese and Chinese characters

### ISSUE THREAD

**Issue by kaiyuhou** [m1k1o/neko#190]
I just tried the latest `arm-chromium` and `arm-firefox`, and noticed that the Japanese/Chinese fonts cannot be correct showed. I think there should be some fonts missing in the `arm-base`. As shown on the screen capture below, this is the Japanese version of Youtube.

![image](https://user-images.githubusercontent.com/11606036/182069195-9a842d76-3704-4b88-bd2b-106e146fd3b6.png)

**Comment by kaiyuhou** [comment]
Here is a compromised solution for those who do not want to recompile the whole `arm-base`

After starting the image:
```shell
docker exec -it [ContainerID] /bin/bash
root@[ContainerID]:/# apt update
root@[ContainerID]:/# apt install -y locates ttf-wqy-zenhei    # or fonts-takao-mincho, fonts-wqy-zenhei
root@[ContainerID]:/# locale-gen en_US.UTF-8                    # not sure if really matter
```
Then, Japanese/Chinese characters can be correctly rendered.

**Comment by m1k1o** [comment]
It has been added recently https://github.com/m1k1o/neko/commit/7d71fd2bc6437a508191684210805746e07deb96 but arm containers are not built automatically, so they are mostly outdated (see [docs](https://github.com/m1k1o/neko/blob/master/docs/getting-started/README.md?plain=1#L24)).
