### ISSUE TITLE
Add Opera browser

### ISSUE THREAD

**Issue by m1k1o** [m1k1o/neko#195]
I just noticed we are missing that major browser that is also available for linux. Would be a nice addition.

It's quite popular and I doubt we get Safari for linux:
![image](https://user-images.githubusercontent.com/7534274/185766799-e3b689f1-4b23-448f-978f-eb97d600ba23.png)

**Comment by RisedSky** [comment]
Opera is very great, i will use it for sure if it's there :)

**Comment by prophetofxenu** [comment]
I'd like to take a shot at this, unless someone else is already working on it.

**Comment by m1k1o** [comment]
I don't know about anyone working on it, feel free to start with it.
