### ISSUE TITLE
(VAAPI HW encoding) Black Screen Since Last Docker Update

### ISSUE THREAD

**Issue by BradleyShaner** [m1k1o/neko#204]
Two days ago, there was a docker image update for all of the containers and I've tried several of them and they all fail exactly the same. It's just a black screen. xfce, firefox, latest, etc, they all just load a black screen. People can join but nothing ever loads.

It would be nice if you used release tags and allowed old versions to exist for issues like this. I wish I could roll back but only the latest tags are available on dockerhub.

I'm running on Unraid.

![image](https://user-images.githubusercontent.com/9120519/192069114-4d110858-a798-4c1b-8426-370d95f621d7.png)

All logs:
[New folder.zip](https://github.com/m1k1o/neko/files/9637483/New.folder.zip)

**Comment by m1k1o** [comment]
What browser do you use? Safari?

> It would be nice if you used release tags

They are on ghcr but only with major release. I should change it to reflect every change that i make, to have them tagged.

**Comment by m1k1o** [comment]
I see you are using `vaapivp8enc` so **hardware encoding**. And it says `stat: cannot statx '/dev/dri/render*': No such file or directory`. Do you have properly mounted your GPU to your container?

**Comment by BradleyShaner** [comment]
Here it is without VAAPI. I tried everything and nothing works. [logs.zip](https://github.com/m1k1o/neko/files/9638764/logs.zip)

Same black screen.
