### ISSUE TITLE
[Question] embed only application

### ISSUE THREAD

**Issue by knackstedt** [m1k1o/neko#207]
Is it possible to only embed the webrtc video player in **my** frontend app by pointing to a URI that I reverse proxy through nginx?

My use case is that I am developing a special remote desktop manager and I want to make the most of webrtc, but the Google machine hasn't given me much relevant information.

**Comment by m1k1o** [comment]
There are [libs](https://github.com/m1k1o/neko/blob/master/client/src/lib.ts) publicly available that can be exported. But there is not much documentation about it.

**Comment by knackstedt** [comment]
Thanks
