### ISSUE TITLE
not working with oracle free tier ARM server

### ISSUE THREAD

**Issue by BK8000L** [m1k1o/neko#212]
Firefox tab crashes when i try to play sound (no errors in docker logs), chromium wants chromium-sandbox package(as seen in docker logs). sancho41/neko:arm-firefox works fine
ubuntu 22.04

**Comment by m1k1o** [comment]
ARM images are not in CI. Since the addition of GPU encoding for Intel VAAPI they broke ghcr pipelines. PR fixing this is welcomed.

**Comment by m1k1o** [comment]
Added proper ARM CI in 32472a70bc51c4b8c0054da4951ad6128eb8be37.

You can now use ARM images:

- `ghcr.io/m1k1o/neko/arm-firefox:latest`
- `ghcr.io/m1k1o/neko/arm-chromium:latest`
- `ghcr.io/m1k1o/neko/arm-ungoogled-chromium:latest`
- `ghcr.io/m1k1o/neko/arm-vlc:latest`
- `ghcr.io/m1k1o/neko/arm-xfce:latest`

Or build ARM images `./build arm-base` and `./build arm-firefox`.

**Comment by DawnElixir** [comment]
> Added proper ARM CI in [32472a7](https://github.com/m1k1o/neko/commit/32472a70bc51c4b8c0054da4951ad6128eb8be37).
> 
> You can now use ARM images:
> 
> * `ghcr.io/m1k1o/neko/arm-firefox:latest`
> * `ghcr.io/m1k1o/neko/arm-chromium:latest`
> * `ghcr.io/m1k1o/neko/arm-ungoogled-chromium:latest`
> * `ghcr.io/m1k1o/neko/arm-vlc:latest`
> * `ghcr.io/m1k1o/neko/arm-xfce:latest`
> 
> Or build ARM images `./build arm-base` and `./build arm-firefox`.

May I know if these ARM images mentioned in the doc have been built? Can't pull with above links and not found in the[packages](https://github.com/m1k1o?tab=packages&repo_name=neko)

**Comment by m1k1o** [comment]
Thanks for reporting. Looks like I needed to go through all of them and change visibility to public. They should be available now.
