### ISSUE TITLE
Audio calls support

### ISSUE THREAD

**Issue by alanmilinovic** [m1k1o/neko#216]
Hi, I find this project as an great collaboration tool with amazing performance in terms of sharing any content to other people.
Chat functionality together with keyboard control is also great.

Now, to go one step further I am wondering if it would be possible to have audio calls supported as well. Maybe even video calls, were you could bring collaboration to even higher level.

**Comment by yesBad** [comment]
https://neko.m1k1o.net/#/non-goals

**Comment by m1k1o** [comment]
Yes, that is non-goal. I can image either creating a new project that embeds neko and adds this functionality, or some kind of plugins for neko, where audio calls would be one of it.

**Comment by alanmilinovic** [comment]
Ok, tnx, for explanation.
