### ISSUE TITLE
Preserve changes

### ISSUE THREAD

**Issue by alanmilinovic** [m1k1o/neko#223]
Is it possible to preserve settings made in browser images. For example if I enable bookmarks and add some bookmarks.
After updating neko and creating container with "up" command all my bookmarks are gone.

**Comment by m1k1o** [comment]
Yes, you need to mount browser profile as volume. That is `/home/neko/.config/google-chrome` for google chrome and similarly for others:
![image](https://user-images.githubusercontent.com/7534274/202905507-230c181e-50d4-403f-af20-88fcf43888c2.png)

**Comment by m1k1o** [comment]
Added to docs. https://neko.m1k1o.net/#/getting-started/?id=want-to-preserve-browser-data-between-restarts

**Comment by alanmilinovic** [comment]
I just tried but I get only black screen?

**Comment by alanmilinovic** [comment]
My configuration is.

```
volumes:
      - ${PWD}/data:/home/neko/.config/google-chrome
      - ${PWD}/policies.json:/etc/opt/chrome/policies/managed/policies.json
```

and in policy file

```
  "DefaultCookiesSetting": 1,
  "RestoreOnStartup": 1,
```

**Comment by alanmilinovic** [comment]
Ok, figured out, it was folder permissions.
