### ISSUE TITLE
Not an issue but please read.

### ISSUE THREAD

**Issue by DillFrescott** [m1k1o/neko#23]
This fork is amazing!! I'm not sure if its the stereo audio or the bitrate is increased but music sounds amazing compared to the main neko project!

Please keep this up!!!!!!

**Comment by m1k1o** [comment]
Hi, great to hear some feedback, thanks!

Yes, the audio has been improved. Now it is stereo. And also bitrate was changed, from `64 kbps` to `128 kbps` . You can even set it to custom value using `NEKO_AUDIO_BITRATE` if you want.

**Comment by DillFrescott** [comment]
Awesome! Thanks for the info!

**Comment by ata-star** [comment]
Lots of thanks from us too, we use it daily
