### ISSUE TITLE
No browser window (black screen with cursor only) with most builds

### ISSUE THREAD

**Issue by suckerfish** [m1k1o/neko#231]
'latest', 'firefox', 'opera', 'xfce', 'vlc', and 'vncviewer'  all seem to work fine. 

For nearly everything else, the behavior is the same. Black screen with a cursor only. Notably I'd prefer to use Chrome or Chromium but same problem with both.

Running on Unraid, but have also tried bare metal on Linux Mint, as well as a Lubuntu VM. Same behavior no matter the platform.  

Log output for chromium attempt here: https://pastebin.com/qfVRtQUu

Feels like I'm missing something pretty basic here but I've been over documentation a lot and not sure what I'm missing.

**Comment by m1k1o** [comment]
I just tried it with latest `m1k1o/neko:chromium` and it works fine.

It looks like this error `pthread_create failed: Operation not permitted` is permitting any executabe to start in your docker container, browser, openbox and neko as well. Maybe its some [bug with your docker runtime](https://github.com/containers/skopeo/issues/1501)? What is your docker version?

I'm on ubuntu 20.04, Docker version `20.10.22, build 3a2c30b`.

**Comment by suckerfish** [comment]
Mint 20
Docker version 20.10.8. 

However, here's an attempt on my Unraid box (running 6.11.5, latest) which is running a much newer version of Docker: 20.10.21, build baeda1f.

Not exactly the same errors, but same result. Black screen with cursor and nothing else. I'm running out of systems to try this on.

https://pastebin.com/dKwzLp20

**Comment by m1k1o** [comment]
This latest error looks like there is no `--cap-add=SYS_ADMIN`. Firefox works without this capability, that should be working for you in any case.

**Comment by suckerfish** [comment]
I did some brief searches on --cap-add=SYS_ADMIN but don't fully understand it. Is this something I can add or enable in my environment to support this?

**Comment by m1k1o** [comment]
Capabilities of container. Normally set up with `docker run` command, or in `docker-compose.yaml` file.

**Comment by suckerfish** [comment]
> Capabilities of container. Normally set up with `docker run` command, or in `docker-compose.yaml` file.

Well that was easy. That seems to have fixed it. Thank you!
