### ISSUE TITLE
RTMP does not work

### ISSUE THREAD

**Issue by phere-x** [m1k1o/neko#236]
Tested sending a stream to the URL manually & it works (using ffmpeg). Tried different services on neko & still did not work. Also tried different images (VLC & Chromium). 

I did both, passing it as an ENV & manually inputting it through UI

logs:
```docker
2023-01-15 17:31:14,904 DEBG 'neko' stdout output:
5:31PM INF starting pipeline module=capture src=rtmp://lhr08.contribute.live-video.net/app/<MYT_STREAM_KEY> submodule=broadcast url=rtmp://lhr08.contribute.live-video.net/app/<MYT_STREAM_KEY>
2023-01-15 17:31:14,904 DEBG 'neko' stdout output:
(neko:14): GLib-GObject-WARNING **: 17:31:14.904: invalid cast from 'GstRtmp2Src' to 'GstPipeline'
(neko:14): GStreamer-CRITICAL **: 17:31:14.904: gst_bus_add_watch_full: assertion 'GST_IS_BUS (bus)' failed
(neko:14): GStreamer-CRITICAL **: 17:31:14.904: gst_object_unref: assertion 'object != NULL' failed
```

```
  nek:
    container_name: nek1
    image: "m1k1o/neko:google-chrome"
    restart: "unless-stopped"
    shm_size: "4gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: 1600x900@60
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_NAT1TO1: 192.168.1.100
      NEKO_UDPMUX: 52100
      NEKO_EPR: 52000-52100
      NEKO_CONTROL_PROTECTION: "true"
      NEKO_LOCKS: control login file_transfer
      NEKO_ICELITE: "true"
      NEKO_ICESERVER: stun:stun.l.google.com:19302
      NEKO_MAX_FPS: 25
      NEKO_BROADCAST_PIPELINE: rtmp://lhr08.contribute.live-video.net/app/<MYT_STREAM_KEY>
```

**Comment by m1k1o** [comment]
In [`NEKO_BROADCAST_PIPELINE`](https://neko.m1k1o.net/#/getting-started/configuration?id=neko_broadcast_pipeline) you are supposed to define full pipeline. If you want to only specify RTMP URL you can do so in GUI as admin:

![image](https://user-images.githubusercontent.com/7534274/212564219-b94c667a-45d3-439f-92c3-44735be4b7ed.png)

Or you can set [`NEKO_BROADCAST_URL`](https://neko.m1k1o.net/#/getting-started/configuration?id=neko_broadcast_url), what automatically starts braodcasting when server starts.

**Comment by phere-x** [comment]
I made the change to `NEKO_BROADCAST_URL`, but I had been using the GUI method. I realized when the container is first started it doesn't stream & I have to stop & start it again for it to work.

**Comment by phere-x** [comment]
This doesn't appear to be an explicit issue on neko's end so I'll close this.
