### ISSUE TITLE
How do I add custom default extensions for Firefox?

### ISSUE THREAD

**Issue by DillFrescott** [m1k1o/neko#24]
I have Surfshark as my VPN provider, is there a way to have the Surfshark extension installed by default and remove the Nord VPN one?

If this is possible please let me know! :)

**Comment by DillFrescott** [comment]
Nvm I figured it out

**Comment by fev4** [comment]
@DillFrescott How did you do this? Would be great to know. Thanks in any case

**Comment by DillFrescott** [comment]
@fev4 I apologize I probably should have put how I did it here because I don't really remember. 

Thinking back, I believe that I edited the files by `exec -it` ing into the container. 

@m1k1o would most likely have an even better and easier way to do it, since he is the creator of this amazing fork!

**Comment by mbattista** [comment]
Custom extensions can be installed via mounting a file into the container:
https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks

The `-v` example would be for a docker run, if you want to use it in a docker-compose file add a volumes parameter to the compose file https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes

Hope this could help you.
