### ISSUE TITLE
How to embed a different chat over/beside current chat?

### ISSUE THREAD

**Issue by phere-x** [m1k1o/neko#242]
I want to have a twitch chat available as an option in one of the tabs for the already existing users from twitch & the community there (& to get my emotes from 3rd party sites & 7TV features, like overlay emotes & patterned usernames). 

I found that running this & streaming it to a channel on twitch gets more viewers in & helps build a watch party community as opposed to just running neko & only inviting the Discord members I can reach. 

There are downsides to using twitch chat like not being self-hosted & so not in charge & being at the mercy of the rules they set. But it's a good option for now till neko chat evolves more. 

Ideally I'd like to aggregate everyone over to this one place, and one step to get closer to do that would be embedding a 'video player' (twitch in my case) & have it as a tab to switch between like with chat would be great.

I have no experience with vue so the most straight forward solution would be greatly appreciated.

**Comment by Technetium1** [comment]
Use Tampermonkey + CSS to hide chat and [make an iframe with Twitch chat](https://dev.twitch.tv/docs/embed/chat/)?

**Comment by phere-x** [comment]
Not ideal to get everyone to install scripts. I'd rather find what to change/edit, and do that. I don't mind having to edit & build it myself when needed.

**Comment by Technetium1** [comment]
The idea was to create and style it how you want, then request those features be implemented by someone more familiar with the codebase. If you're not comfortable creating it yourself, that's always fine too!

**Comment by m1k1o** [comment]
You can create this tampermonkey and CSS changes, and when ready just adding it to your image (by modifying index.html) so your users don't need to do it using extensions and everybody sees it.
