### ISSUE TITLE
Without docker and/or SSL in Neko

### ISSUE THREAD

**Issue by grbfst** [m1k1o/neko#243]
I'm trying to run Neko without docker to no avail. I've done all things in the base docker file but I get a lot of dbus errors.
When using it in Docker I can't get SSL working,

**Comment by yesBad** [comment]
What's your issue with "can't get SSL working"? I myself just reverse proxy it-

**Comment by m1k1o** [comment]
Yes, using reverse proxy is the best way how to do it. But if you want neko to handle SSL, you only need to specify path of your cert `NEKO_CERT=/your/cert` and key `NEKO_KEY=/your/key`. That should give you SSL.

**Comment by Xeddius** [comment]
> I'm trying to run Neko without docker to no avail. I've done all things in the base docker file but I get a lot of dbus errors. When using it in Docker I can't get SSL working.
Let me know if you've solved this!

Caddy V2 is great for this. It supports automatic SSL using letsencrypt.
All you have to do is install Caddy V2 (which also supports docker) and add settings like this to the config (Named Caddyfile) and of course be sure to change the appropriate values for IP address, port, and website name.


You can have this up and running in a few minutes with this setup.
```
{
        http_port 80
        https_port 443
}
websitehere.com {
        reverse_proxy * 192.168.1.0:8080 {
    header_up Host {host}
    header_up X-Real-IP {remote_host}
    header_up X-Forwarded-For {remote_host}
    header_up X-Forwarded-Proto {scheme}
  }
}
```

**Comment by grbfst** [comment]
Well, thanks to reverse proxy I got it running indeed. Many thanks.

How would I start with a clean slate every time I start Neko (without Docker)? I don't want a browser to remember history and don't want to autostart Neko with an already logged in admin.

**Comment by m1k1o** [comment]
You can set up browser to not store any history. If you mean logged in admin for neko, you need to logout because it is tored in local storage in your browser.

**Comment by aptdnfapt** [comment]
those of you goin through the pain of gettig cert getting domain and reverse proxy ++other bs just to watch some vids with 10-at max 20 ppl . yall just can use tailscale . no need to set up reverse proxy . just add you friends devices to your tailscale net and enjoy . ask ai if u dont get a thing
