### ISSUE TITLE
Login to Neko

### ISSUE THREAD

**Issue by p6002** [m1k1o/neko#245]
What is a login to Neko after deploying container using your docker-compose file?

**Comment by mbattista** [comment]
Hi,

the passwords you provided with the composer file.
The defaults are:
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin

Those passwords work with every username. Everyone using the admin password will be admin, everyone using the password will be a normal user.

Documentation:
https://neko.m1k1o.net/#/getting-started/configuration
