### ISSUE TITLE
The possibility to auto hide the top and bottom bars

### ISSUE THREAD

**Issue by 304442** [m1k1o/neko#254]
Can this feature be added?
The possibility to auto hide the top and bottom bars

**Comment by m1k1o** [comment]
There is fullscreen button, or if you visit the page with ?cast=1 then only video feed is visible. But I suspect you want to have chat visible, right?

**Comment by m1k1o** [comment]
That could be added. Yes.

**Comment by m1k1o** [comment]
Added controls for `?cast=1`:
![image](https://user-images.githubusercontent.com/7534274/220987490-7c905332-17aa-4fab-8b4c-6b8d9fa7fc8d.png)

**Comment by alanmilinovic** [comment]
If you are not logged in. It will display menu on the right, when using ?cast=1 and you will not be able to login.

**Comment by m1k1o** [comment]
This looks like some forgotten styles for mobile devices for `?cast=1`. Thanks for pointing out!
