### ISSUE TITLE
Questions about use

### ISSUE THREAD

**Issue by Mrs-Feathers** [m1k1o/neko#255]
1. is it possible to stream the video feed as an embed to a website? if i can get a video feed, i can use it for website stuff, and even put it into our vrchat world for events that use a browser.. like using airconsole and thus instant game console in vrchat only possible using something like neko. 
2. i've seen some people say local networks don't work but i've seen some people say they've found a way around it.. but weren't really clear about that. so i ask, is supporting a local network able to be done? i host it and everyone can use it, but i have to use a proxy if i want to sign in.. it'd be neat if it could just work locally.
and thats about it for questions. i absolutely love this and proudly support it as its quickly becomming very used in our little online community here at Furry Refuge :)

**Comment by yesBad** [comment]
1. yes possible
2. mine works locally & externally perfectly
