### ISSUE TITLE
[Feat] Hide the screen cursor so that we can use the client browser to control the internal browser

### ISSUE THREAD

**Issue by BranceLee** [m1k1o/neko#256]
I tried adding the `"/usr/bin/X -retro -nocursor -config /etc/neko/xorg.conf :99.0"` to start the x server, the basic xorg cursor disappeared but when I open the `openbox` or start `google-chrome` still shows the internal cursor shows again I also tried the `XDefineCursor` on the XDisplayOpen function to set the cursor as transparent or use the `XFixesHideCursor` function, but it still shows the cursor, any suggestion to meet this feature. Thanks

**Comment by m1k1o** [comment]
Ximagesrc for gstreamer has setting use-cursor=true

**Comment by BranceLee** [comment]
I found another way to solve it by using `"unclutter -idle 0 -jitter 10000 -d " + display`, the move event will be hidden and the click event will be revered, but your solution could be better, Thanks!
