### ISSUE TITLE
Possible without exposing public port

### ISSUE THREAD

**Issue by bobobobosu** [m1k1o/neko#259]
Is it possible to leverage WebRTC nat traversal to allow for incoming connection without exposing port to public? I mean just like how chrome remote desktop does with stun and turn relay.

**Comment by m1k1o** [comment]
Yes, you can configure own ICE servers, that will be turn servers. In that case you do not need to expose any port.

**Comment by bobobobosu** [comment]
Is it possible without turn servers? This is what I get when accessing neko behind a reverse proxy with only the website port exposed. Neko works, however, if it is on the same lan as the client.

`2:09AM WRN could not get server reflexive address udp6 stun:stun.l.google.com:19302: read udp6 [::]:59058: i/o timeout module=webrtc submodule=pion subsystem=ice
2:09AM INF sent all ICECandidates module=webrtc
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice
2:09AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice`


This is a screenshot from chrome://webrtc-internals
<img width="1416" alt="Screenshot 2023-03-16 at 10 14 43 PM" src="https://user-images.githubusercontent.com/57658704/225794878-afe53532-c534-4d67-ab38-85874e56a298.png">


Neko is in school network with only ipv4, client is also in a school network.

**Comment by m1k1o** [comment]
It looks like there is some error when gathering client's candidates. Its not needed when ports are exposed, so that might be why it was never actually discovered. Also propert ice tricke is missing on client side, to send candidates asynchronously.

**Comment by m1k1o** [comment]
With the latest changes it should be fixed. I was able to test connection with only private TURN and STUN servers. 

```bash
'NEKO_ICESERVERS=[{"urls": ["turn:<ip>:3478", "stun:<ip>:3478"], "username": "<user>", "credential": "<pass>"}]'
```

@bobobobosu can you please check again if it fixes your issue?

**Comment by bobobobosu** [comment]
Works now!! This is awesome!
