### ISSUE TITLE
How to disable kde lock screen on plasma container

### ISSUE THREAD

**Issue by dillfrescott** [m1k1o/neko#266]
There is no lock screen option in settings :(

This is a big issue because the screen will lock while watching a movie or show and block the view obviously.

**Comment by m1k1o** [comment]
This looks relevant: https://superuser.com/a/1768085 I'll take a look later today.

**Comment by m1k1o** [comment]
Could you try running `docker neko exec kwriteconfig5 --file ~/.config/kscreenlockerrc --group Daemon --key Autolock false;` ?

**Comment by m1k1o** [comment]
@dillfrescott fixed in latest release.

**Comment by dillfrescott** [comment]
Ok awesome!
