### ISSUE TITLE
Audio does not work in KDE

### ISSUE THREAD

**Issue by vincent-163** [m1k1o/neko#267]
Here is /var/log/neko/pulseaudio.log: `[pulseaudio.log](https://github.com/m1k1o/neko/files/11072189/pulseaudio.log)` 
The log looks perfectly normal, and audio is working in firefox, not sure why it doesn't work in KDE (no devices are visible). I tried creating virtual sinks via `pacmd load-module module-null-sink sink_name=MySink` but I got `Daemon not responding.`. Any ideas on how to get audio working on KDE?

**Comment by m1k1o** [comment]
Despite it being hidden from KDE control panel and only shown as inactive, it works.
![image](https://user-images.githubusercontent.com/7534274/227790009-81c89b95-26dd-4134-b5e9-2fd17e2250f5.png)

Tried multiple applications and even volume changing works.
![image](https://user-images.githubusercontent.com/7534274/227790042-fb6b4d7e-e3f6-4da2-bc97-dec6922b20fc.png)

**Comment by m1k1o** [comment]
It looks like the default pulseaudio sink `auto_null` is intentionally ignored by KDE. Renaming audio sink fixes this issue.

**Comment by vincent-163** [comment]
Thanks for the update. I tried out the latest image `m1k1o/neko:kde` after the update but things have not changed: ![photo](https://user-images.githubusercontent.com/36415725/227793970-1220d23a-7353-4ba4-9f34-42ed956aeb5b.jpg)
There are no audio devices shown before and after the update.

The host operating system is a fresh Ubuntu 22.04 Server (no gui installed) on Hetzner Cloud in case that matters. It also has `cap_add: - SYS_ADMIN` in order to enable Chrome. The other tested image was Firefox, where audio does work.

**Comment by vincent-163** [comment]
Sorry, I forgot to mention that I also mounted an empty directory with owner 1000:1000 to `/home/neko` inside the container. It seems that an empty directory lacked the configuration needed to get audio working, and that was the actual reason. Sorry for the disruption.

**Comment by m1k1o** [comment]
Glad it works. Yes, it is missing `~/.config/pulse/client.conf` file, that should contain `default-server=unix:/tmp/pulseaudio.socket`.  Maybe there is some way how to get rid of this dependency and allow users mounting whole home directory in the future.

**Comment by m1k1o** [comment]
According to [their documentation](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Network/), adding env `PULSE_SERVER=unix:/tmp/pulseaudio.socket` should fix the problem and remove the need for client.conf.

**Comment by ehfd** [comment]
In my case, using KMix instead of plasma-pa is one way to fix it.
