### ISSUE TITLE
Hey, how do I use the new nvidia acceleration?

### ISSUE THREAD

**Issue by heryoff** [m1k1o/neko#273]
I tried running the compose file on the repository with google-chrome, but it seems to just don't work. Stuck in loading.

Windows running wsl 2 Ubuntu

**Comment by m1k1o** [comment]
The compose file on the repository is not using GPU acceleration.

Here are some examples how to use that:
https://neko.m1k1o.net/#/getting-started/?id=nvidia-gpu-acceleration
Though it was only tested on linux.

If its stuck in loading, please make sure you have set up IP correctly:
https://neko.m1k1o.net/#/getting-started/?id=networking
