### ISSUE TITLE
Using self-hosted TURN Server 

### ISSUE THREAD

**Issue by ralfi** [m1k1o/neko#275]
Hi,

based on my **working** Matrix / Nextcloud configuration with my own "hetzner-based" COTURN Server i try to adapt these settings for neko, bui it do not work. Seems to me it is related to my TURN secret or something like that. Here is the VAR def: 

`NEKO_ICESERVERS: "[{"urls": ["turn:<MY-COTURN-SERVER>:443?transport=udp", "turn:<MY-COTURN-SERVER>:443?transport=tcp", "turns:<MY-COTURN-SERVER>:443?transport=udp", "turns:<MY-COTURN-SERVER>:443?transport=tcp"], "credential": "<MY-COTURN-CREDENTIAL"}, {"urls": ["stun:stun.nextcloud.com:443"]}]"`

What could be wrong there?
Thank you!

**Comment by m1k1o** [comment]
For first sight, i see that you use ", try switching to ' for env because json uses ".

**Comment by yesBad** [comment]
Mine have been set like so:
`- 'NEKO_ICESERVERS= [{"urls": ["turn:66.222.333.333:3478", "stun:66.222.333.333:3478"], "username": "Your", "credential": "Creds"}]'`

**Comment by ralfi** [comment]
> Mine have been set like so in the docker-compose.yml: `- 'NEKO_ICESERVERS= [{"urls": ["turn:66.222.333.333:3478", "stun:66.222.333.333:3478"], "username": "Your", "credential": "Creds"}]'`

Mmmh, in which docker-compose section do you have this setting? And how do you define your username? docker-compose appears with error but triple syntax check sseems to be okay.

**Comment by yesBad** [comment]
> Mmmh, in which docker-compose section do you have this setting? And how do you define your username? docker-compose appears with error but triple syntax check and seems to be okay.

I'll send you my Docker compose in about an hour!

**Comment by ralfi** [comment]
Thank you! I must learn the syntax ...

**Comment by ralfi** [comment]
> > > Mmmh, in which docker-compose section do you have this setting? And how do you define your username? docker-compose appears with error but triple syntax check and seems to be okay.
> > 
> > 
> > I'll send you my Docker compose in about an hour!
> 
> https://ili.cx/t/nekoconf <-- There you go! :)

Hi yesBad,

i am a little bit confused and not a expert for TURN configuration. Jitsi needs only TURN / TURNS server var and only the static-auth-secret string,  matrix-synapse the same. But whithout these or similar vars in the docker-compose yaml the connection to my coturn server do not work. 

Can you please explain how i can set these vars for neko?

**Comment by yesBad** [comment]
I'm sorry I have no clue about such. I just setup a simple coturn, set password & username and that is it.

**Comment by m1k1o** [comment]
I also just use password. There is some Oauth option for authentication but its not implemented for neko. Can you switch to password auth?

**Comment by ralfi** [comment]
![ksnip_20230417-144513](https://user-images.githubusercontent.com/294423/232488683-a3c153b5-d9ce-43f1-b636-c84075232a61.png)

These is my complete turnserver.conf (Debian / coturn Package)
How can i do this?
