### ISSUE TITLE
Manage Browser Settings/Extensions

### ISSUE THREAD

**Issue by itguy327** [m1k1o/neko#280]
"Managed by Policy" and can't remove any extensions. Extensions can leak information and run code I would not otherwise allow.

Is there any way to remove these restrictions

**Comment by m1k1o** [comment]
It is hard to meet requirements of all people. Therefore default settings are chosen to match the most usecases. For privacy consious users with custom needs, it is expected that they will change the settings accordingly.
https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks

**Comment by itguy327** [comment]
Thank you. Sorry for the questions, just getting started and going to fast

**Comment by itguy327** [comment]
Can extensions be removed completely?

**Comment by m1k1o** [comment]
Yes. Once you mount your own policy file, you can just remove them in the file.

**Comment by itguy327** [comment]
Where in the policy file are these and are they required for functionality? Thank you

![Screenshot_20230408-083159](https://user-images.githubusercontent.com/2548760/230721465-c574b033-0c13-4219-a8d2-d38b125aa1d1.png)

**Comment by m1k1o** [comment]
Here:
https://github.com/m1k1o/neko/blob/9bdf9c88511d8adbadc59a557a5cf967eb2039ae/.docker/google-chrome/policies.json#L28-L35

You need to copy this file locally and mount it as volume for neko. 

```yaml
  volumes:
    - "./policies.json:/etc/opt/chrome/policies/managed/policies.json"
```

You can replace with your own extensions, or remove all so none are there.

**Comment by itguy327** [comment]
Thank you
