### ISSUE TITLE
download / upload (not clear from readme)

### ISSUE THREAD

**Issue by innerop** [m1k1o/neko#281]
Hi,

How do I download an image shown inside the virtual browser to my local machine? If I right click on the image inside the virtual browser and choose Save As then which folder do I need to save it to (is that configurable?) so that it will show up in the downloads folders on the Files tab in Neko? 

To upload a file from my local machine, which folder I have to place that file in my local machine (is that configurable)? 

I couldn't follow from watching the animated GIF in the Readme.

Thanks

**Comment by m1k1o** [comment]
Add `NEKO_FILE_TRANSFER_ENABLED=true` to docker-compose and new menu with files will be shown. There you can upload/download files as shown in animated GIF.

**Comment by innerop** [comment]
Ok, thank you. I guess I'll have to look closer at what is going on in the GIF. Not sure when it starts and ends, and the text is blurry. But I'm sure it's intuitive once I try it.

**Comment by CreeperSword** [comment]
I have "NEKO_FILE_TRANSFER_ENABLED: true" in my docker-compose.yaml, but the file menu doesn't show up. If i set it to "NEKO_FILE_TRANSFER_ENABLED=true", whenever i try to start neko it gives me an error saying it's missing a colon.

**Comment by m1k1o** [comment]
Docker compose supports two ways how to add environment variables:

- As map: `key: "value"`
- As array: `- "key=value"`

Please make sure you choose to use one of there ways and you don't mix them.
