### ISSUE TITLE
VLC play stucked

### ISSUE THREAD

**Issue by xushier** [m1k1o/neko#283]
### My device、env & configs:
cpu: i9-9900
gpu: intel uhd 630
network: UP:1000Mbps
docker: 
```
docker run
  -d
  --name='Neko-Vlc'
  --net='bridge'
  --privileged=true
  -e 'NEKO_PASSWORD'='xxx'
  -e 'NEKO_PASSWORD_ADMIN'='xxx@'
  -e 'NEKO_NAT1TO1'=''
  -e 'NEKO_ICELITE'='true'
  -e 'NEKO_VP8'='true'
  -e 'NEKO_VP9'='false'
  -e 'NEKO_H264'='false'
  -e 'NEKO_VIDEO_BITRATE'='2500'
  -e 'NEKO_MAX_FPS'='25'
  -e 'NEKO_AUDIO_BITRATE'='128'
  -e 'NEKO_FILE_TRANSFER_ENABLED'='true'
  -e 'NEKO_HWENC'='vaapi'
  -e 'NEKO_CONTROL_PROTECTION'='true'
  -e 'NEKO_FILE_TRANSFER_PATH'='/home/neko/Downloads'
  -e 'NEKO_IPFETCH'='https://checkip.amazonaws.com'
  -e 'NEKO_PROXY'='true'
  -e 'NEKO_BIND'=':8080'
  -e 'NEKO_LOCKS'='file_transfer control'
  -e 'NEKO_IMPLICIT_CONTROL'='false'
  -e 'NEKO_EPR'='52000-52100'
  -e 'NEKO_SCREEN'='1600x900@60'
  -p '6531:8080/tcp'
  -p '52000-52100:52000-52100/udp'
  -v '/mnt/user':'/mnt':'rw'
  -v '/mnt/user/appdata/Neko-Vlc':'/home/neko/Downloads':'rw'
  --device='/dev/dri/'
  --shm-size="6gb"
  --cap-add=SYS_ADMIN 'ghcr.io/m1k1o/neko/intel-vlc:latest
```

I've tried playing 1080p , x264 and x265 encoded movies and the file sizes are both around 5gb. When playing, the cpu and gpu occupancy are both about 20%, and the performance and network are both redundant.

I think this configuration playback should not freeze. But in fact even if I am the only one watching in the room, and the resolution is turned down, it will still play like powerpoint.

If i don't use vaapi, it will still freeze, but it is slightly better than using vaapi, and the CPU usage will be higher, about 30%.

I want to use vaapi to encode, and the playback will not freeze. How can I configure it?

**Comment by m1k1o** [comment]
I cannot reproduce it. CPU only using `Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz` it yields very good results.

Could you check in media statistics:
![image](https://user-images.githubusercontent.com/7534274/230766019-f299cd45-8583-49a1-bf97-75c58cd7ebad.png)

If you see any lost frames during decoding? 
![image](https://user-images.githubusercontent.com/7534274/230766014-93201f5c-a9cf-488a-8c96-42c96f8c1edb.png)

**Comment by xushier** [comment]
![image](https://user-images.githubusercontent.com/31540107/230767339-2d5f382d-42a8-4b73-ae31-d083e0b1c11c.png)
![image](https://user-images.githubusercontent.com/31540107/230767406-d6505693-85b3-453c-994f-bef2e8b8e0cf.png)
No lost.

**Comment by xushier** [comment]
So, No lost means that the encoding of n.eko is working normally, is the decoding speed not keeping up?

But the graphics card uhd630 has been assigned to n.eko and the call is correct, and the video is also being decoded with vaapi. This work should be more than enough for uhd630, and it should not be stuck.

**Comment by m1k1o** [comment]
It means that VLC can decode video normally. You could see WebRTC internals in google chrome `chrome://webrtc-internals` to see if you get any lost packets.

You could try switching to H264 if that makes difference.

**Comment by xushier** [comment]
Thanks for your answer.

If there is no problem with encoding and decoding, it should be a network problem. My ipv6 network bandwidth is large enough, but the ipv4 bandwidth is only 60Mbps, which may be caused by the slow speed of the ipv4 network.

Anyway, using the ipv6 network alone does not cause playback lag.

Finally, I changed the network mode of the container from bridge to host, and now the ipv4 network also looks normal.
