### ISSUE TITLE
Question about NEKO_PASSWORD* and diff between admin and user

### ISSUE THREAD

**Issue by innerop** [m1k1o/neko#288]
Hi, 

I searched this repo for all occurence of NEKO_PASSWORD* to see how the access control mechanism is implemented. I could only find references in Dockerfile for base, docker-compose.yaml and some docs. Where in the code does it test if the entered value == NEKO_PASSWORD*? is it in the frontend code? I can't seem to be able to find the place in the code where the test is performed, and where in the code it recognizes that the user is admin or regular?

A related question: what is the difference between admin and user? I can't tell. I get the same features it seems. Is the difference documented?

**Comment by innerop** [comment]
I found some privileged functionality protected by the pwd 

Like https://github.com/m1k1o/neko/blob/master/server/internal/http/http.go#L86

But not able to find where the password is checked to allow or not allow login.... Will keep looking

**Comment by m1k1o** [comment]
We use [viper](https://github.com/spf13/viper) that loads configuration from multiple sources, also [from env](https://github.com/spf13/viper#working-with-environment-variables). You can read about it more e.g. here: https://dev.to/techschoolguru/load-config-from-file-environment-variables-in-golang-with-viper-2j2d

Its checked here:
https://github.com/m1k1o/neko/blob/b2080649ea50d942c3e9887813d867edbfc21052/server/internal/websocket/websocket.go#L365-L384
Difference between admin and user is, that admin can:
 - change screen size
 - (un)lock room
 - (un)lock control - also for control protection
 - kick members
 - ban members
 - take control from others
 - give control to others
 - start and stop broadcasting
 - uplaod and download files if file transder is enabled

Screen size:
![image](https://user-images.githubusercontent.com/7534274/232247605-74b3b9a2-c3ed-4dc0-8c0e-d191d42b9a1e.png)

Locks:
![image](https://user-images.githubusercontent.com/7534274/232247616-3121aeba-fa12-41a6-abe2-46198f408478.png)

Context menu for user (right click on avatar):
![image](https://user-images.githubusercontent.com/7534274/232247635-cb1cfde3-4d9c-4799-bed9-ca5deb728ac1.png)

Broadcast (in settings):
![image](https://user-images.githubusercontent.com/7534274/232247660-694190f6-1595-4793-a56b-ab63e0e1f2de.png)

Yes, current documentation could be better. There are many things as comments in issues, it would be nice to go through it all and put it on a page.

**Comment by innerop** [comment]
Yes on the need to update the docs, just not very good at docs myself, but I'll try and see if I have any time, when I free up. Thank you so much for all this info.  At least it's here now in the issues.
