### ISSUE TITLE
[Docs] Running without Docker in GPU mode

### ISSUE THREAD

**Issue by innerop** [m1k1o/neko#290]
Hi @m1k1o,

Is running with GPU support without docker just a matter of copying the commands from base and browser dockerfiles without --disable-gpu in supervisord or is it a much more complex affair? 

Docker is not buying me much since I'm running on my own dedicated box and can keep track of hwo to replicate the environment or simply make snapshots of it. 

I need to run a web app that uses video shaders which rely on WebGL/GPU.

Please let me know the shortest path to getting it to work.

I can format your answer and add it to the Getting Started doc (after I fork this repo) and make a pull request, if extra info is indeed necessary (if it's not simply just running serve-client and start-server)

Thanks

**Comment by innerop** [comment]
Maybe it's not possible to run Neko without VirtualGL? even outside of Docker?

**Comment by innerop** [comment]
This is for an immediate WebGL/WebGPU use case I have, so I can't really wait for VirtualGL issues to be resolved, if there is a way to run without it.

**Comment by m1k1o** [comment]
I explained that in the comment here: https://github.com/m1k1o/neko/issues/228#issuecomment-1356878299

> You could be able to install Neko "natively", I have tried it in one VM. Although there is not proper documentation about this, you would just need to follow steps that are in [Dockerfile](https://github.com/m1k1o/neko/blob/4789b7704f386cc456504d2644c921cdf936ee49/.docker/base/Dockerfile), install on your host system and then just run it. However, I recommend starting with exsiting system that has GUI with desktop manager, is based on Xorg and uses Pulseaudio. For that matter you only need to install gstreamer dependencies, configure pulseaudio properly and run neko binary (you don't need to build it from scratch, you can copy it from docker image). This process would be nice to have documented.

**Comment by innerop** [comment]
Ok, thanks, will give it a try and anend the Getting Started guide in the part where you already mention running neko without Docker (or link to the steps from there)

This is just for running WebGL/WebGPU. I have another question about H265 and AV1 that I'll post in a separate thread.
