### ISSUE TITLE
Disable mouse pointer

### ISSUE THREAD

**Issue by RuralDependencies** [m1k1o/neko#293]
Hi,

Using docker, any way to disable mouse pointer?
Thanks!

**Comment by m1k1o** [comment]
You could copy existing pipeline and add it to neko, but change use-pointer to false in ximage element.

**Comment by RuralDependencies** [comment]
Hmm, indeed yes, I saw in config, nice!

Do you know the default "settings" to match:
```
      NEKO_MAX_FPS: 60
      NEKO_VIDEO_CODEC: h264
      NEKO_VIDEO_BITRATE: 10000
```

using ximage?

**Comment by m1k1o** [comment]
If you start neko and join with one user, you will see full pipeline in logs. That way you can just copy it and use it.
