### ISSUE TITLE
Set neko menu language permament

### ISSUE THREAD

**Issue by ralfi** [m1k1o/neko#295]
Hi folks,

atm the language of the docker container neko menu is set to "en". 
Please make it possible to set another language permanent.

Thanks in advance!
Regards

**Comment by m1k1o** [comment]
Added `?lang=<lang>` parameter.

**Comment by ralfi** [comment]
`Error: positional arguments are not supported: ['?lang=de', '-c', '/etc/neko/supervisord.conf']`

Thanks, but where / how to added? Docker supervisord option do not work

**Comment by m1k1o** [comment]
Its only for URL. `http://<neko>:8080?lang=de`Reasoning from the issue:

> But I thought, that a clear cut between client and server should be kept, so I added it as a URL parameter, which also has the advantage that you can send links in the language you want.

If you have reverse proxy, you can add it there.

**Comment by ralfi** [comment]
Thanks, but adding the language in my apache reverse proxy conf do not work, only in browser.
