### ISSUE TITLE
Question: Limiting UDP ports

### ISSUE THREAD

**Issue by NN-Binary** [m1k1o/neko#298]
Hi,

Just a question, what is the reasoning to use 100 UDP ports? I wish to stay on the multiple ports model, I guess this is to allow up to X persons joining?

Will it break internal features if I use 10 ports? I want a maximum of 4 watchers at a time.

**Comment by m1k1o** [comment]
All those questions are explained in the docs: https://neko.m1k1o.net/#/getting-started/?id=why-so-many-ports

> I guess this is to allow up to X persons joining?

![image](https://user-images.githubusercontent.com/7534274/233858249-955efb8b-e011-4a0a-a465-efb2e660e7af.png)

> Will it break internal features if I use 10 ports?

![image](https://user-images.githubusercontent.com/7534274/233858230-d9d6ddeb-88d4-4cc7-931f-3791917b28f3.png)

**Comment by yesBad** [comment]
You can run a CoTurn server or similar to need even less ports :)
