### ISSUE TITLE
UDP Port change

### ISSUE THREAD

**Issue by RuralDependencies** [m1k1o/neko#299]
The docs state that we can't change the UDP port, is is a technical reason or it has just not been implemented in the codebase (yet)?

**Comment by m1k1o** [comment]
[Docs says](https://neko.m1k1o.net/#/getting-started/?id=why-so-many-ports) you cannot change or limit the mapping `<internal>:<external>` but you can absolutely change them. Just keep in mind, they need to be the same inside container as exposed outside.
