### ISSUE TITLE
New Setup on Hetzner VM: client is not using websocket protocol

### ISSUE THREAD

**Issue by ralfi** [m1k1o/neko#300]
Hi,

based on my complete working install on my home server i try to setup a new install via Hetzner VM.
Same Debian install, same Docker, same Apache Version and Reverse Proxy setup

But at the hetzner this error appears

![image](https://user-images.githubusercontent.com/294423/234611484-f2a94cb9-75ee-4b52-a00c-9223d3c27f68.png)

Apache proxy and wstunnel modules are enabled. How can i debug further?

**Comment by yesBad** [comment]
This could have a bit of help (mostly the 3 commands (probably?)) https://stackoverflow.com/a/27534443/16519490

I didn't know people still use Apache for whatever reason....

**Comment by ralfi** [comment]
Oh, its historic ;-) you know. 
BTW i will change this to Nginx and try again.

**Comment by yesBad** [comment]
Before you even ask, here's working NGINX config for neko: https://ili.cx/t/nekonginx

**Comment by m1k1o** [comment]
Here is default config for apache: https://neko.m1k1o.net/#/getting-started/reverse-proxy?id=apache

**Comment by yesBad** [comment]
> Here is default config for apache: [neko.m1k1o.net/#/getting-started/reverse-proxy?id=apache](https://neko.m1k1o.net/#/getting-started/reverse-proxy?id=apache)

Forgot these existed 👍

**Comment by ralfi** [comment]
Everything works now (with apache) after changing SHM_SIZE related to VM RAM size, checking UDP traffic works and do NOT exposing UDP traffic via `docker-compose.yaml` because it's not needed, all checks with `firefox:latest` image.
