### ISSUE TITLE
WebAuthn authentication support

### ISSUE THREAD

**Issue by YidaozhanYa** [m1k1o/neko#304]

**Comment by mbattista** [comment]
Hi,

Can you please elaborate why would this be needed?
Right now there are two passwords for a neko instance. One for all admin users and one for all normal users.

There is no risk for the user because of a password leak.
Also every user can share the same name and this would not matter.

**Comment by yesBad** [comment]
You could add external security by applying HTTP Basic Authentication in your proxy. As mbattista asked, I don't see any need for this as there's no multi-user support.
