### ISSUE TITLE
Pausing/Resuming ffmpeg

### ISSUE THREAD

**Issue by Korelia** [m1k1o/neko#306]
I would like to do a "pause/resume" on the video, so when for example the user is not focusing on the window, it would simply stop sending data altogether, I don't see anything in the doc about it, is this feature implemented?

**Comment by m1k1o** [comment]
Hi. We don't use ffmpeg at all. But there is not such feature. As long as you are connected you receive data. You can pause video in GUI but it will still receive the data.

But it looks like a nice feature, PRa are welcome.

**Comment by Korelia** [comment]
Thanks! In the current state of things, does it still encode even tho there is no client connected? Or only when client is connected?

**Comment by m1k1o** [comment]
It starts encoding when the first client connects. When there is nobody connected it does not encode anything.

_sure, you can contact me using discord, there is an invitation badge in README to our discord room_
