### ISSUE TITLE
choose browser image if test with ./server-client

### ISSUE THREAD

**Issue by cedricbieder** [m1k1o/neko#307]
Hello great project,

I want to test some of my own changes for my use case, as described in [#287](https://github.com/m1k1o/neko/issues/287#issuecomment-1505112391) I could start the project with ./server-client, problem is, that I cannot login. First this is nothing new, because that is the same issue I have with the build docker too. My solution with the build docker was, just using the chromium-image which works perfect. 
Now to my question, can I choose the image with ./server-client?

The second issue is, that I tried to build my changes and added them with:

```
    volumes: 
      - "/home/user/projects/neko/client/dist:/var/www/dist:ro"
```

to the docker-compose.yaml.

But after I restart, I see no changes (I can see the dist folder in the running docker).
Do you know what the issue here?

Thank you.

**Comment by m1k1o** [comment]
You start your neko container, and then you copy `.env.default` to `.env` where you change `SERVER_PORT` to the port of your neko container. And `CLIENT_PORT` will be where your dev client will be available.

And when mounting, the path inside container should only be `/var/www/`.
