### ISSUE TITLE
Disable Chat

### ISSUE THREAD

**Issue by thehoff** [m1k1o/neko#31]
Not really an issue but is there a way to disable/lock the chat?

I can't seem to find any doco on any fork to do this.

Thanks

**Comment by m1k1o** [comment]
You can do it per user, also implementen in original repository. Muting means, user cannot write to chat anything. But servwe-wide not.

![image](https://user-images.githubusercontent.com/7534274/111140162-5009e300-8582-11eb-8b18-09a49a651d4a.png)

**Comment by Toucan-Sam** [comment]
I'd actually like to see this implemented as well.
We use Discord for most of our comms, but Neko for watch parties.
It's easier to mod chat in Discord, so disabling chat in Neko completely would be ideal.
