### ISSUE TITLE
Restart neko

### ISSUE THREAD

**Issue by grbfst** [m1k1o/neko#313]
Is there a way to restart Neko so it reads the ENV variables again? Sometimes I need to change the user password (before logging in).
Neko stop or the likes don't work.

**Comment by m1k1o** [comment]
Docker doesn't offer this feature, see: https://stackoverflow.com/questions/27812548/how-to-set-an-environment-variable-in-a-running-docker-container

But you could move your configuration to yaml file and you can change it anytime, just restart neko binary to reread it.
https://neko.m1k1o.net/#/getting-started/configuration?id=config-file

**Comment by grbfst** [comment]
Check, how do I restart the binary?

**Comment by m1k1o** [comment]
You can restart the whole container or just run `supervisorctl restart neko` inside the container.
