### ISSUE TITLE
How neko compares to noVNC

### ISSUE THREAD

**Issue by dmikushin** [m1k1o/neko#319]
Hi @m1k1o , as an expert in this topic, could you please explain what are the differences between neko and xfrb+x11vnc+novnc stacks?

**Comment by m1k1o** [comment]
Main difference is that Neko uses webrtc and novnc sends images over websocket connection. Neko as well natively supports audio and binds directly to xvfb/Xdummy instead of using VNC. Neko also supports multiple participants natively.

**Comment by dmikushin** [comment]
What about performance observations? How much network bandwidth Neko consumes compared to noVNC, and what is the price of streaming operations for the CPU load?

**Comment by dmikushin** [comment]
One other aspect is TCP versus UDP. noVNC streams over TCP, which is inefficient, but portable. Is webrtc in Neko based on UDP? Are there any difficulties manipulating Neko's UDP ports through Docker?

**Comment by m1k1o** [comment]
Unicast udp works fine. Only multicast udp needs host network and we don't use that here.
