### ISSUE TITLE
Dear Master Neko, thank you!

### ISSUE THREAD

**Issue by 00000o1** [m1k1o/neko#321]
Thank you, dear Master Neko @m1k1o ! 🧙🏻 🐈‍⬛ 🏰

I managed to fix a weird Chrome bug that was happening while I was dockerizing my project. In order to fix it, I made use of your venerable, intelligent, brilliant and highly useful chrome flags, from:

[neko/.docker/chromium/super…](https://github.com/m1k1o/neko/blob/8ef9c1aff5d68bfec22382ee60ecfa2c93bba752/.docker/chromium/supervisord.nvidia.conf)

❤️ 

Thank you so very much, dear kind Neko Master!

**Comment by yesBad** [comment]
Cool 👍

**Comment by m1k1o** [comment]
Thank you for the appreciation! Please consider [sponsoring this project](https://github.com/sponsors/m1k1o) to support further development. 🙏❤️

**Comment by 00000o1** [comment]
Sir I have done so! Please enjoy your well earned gold! ⚱️💙
