### ISSUE TITLE
always reconnecting in login

### ISSUE THREAD

**Issue by ZsiGiT** [m1k1o/neko#323]
My portainer stack settings:

version: "3.4"
services:
  neko:
    image: "m1k1o/neko:microsoft-edge"
    cap_add:
      - SYS_ADMIN
    restart: "unless-stopped"
    shm_size: "4gb"
    ports:
      - "8586:8080"
      - "8045:8045/tcp"
      - "8046:8046/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: *****userpassword
      NEKO_PASSWORD_ADMIN: ****adminpassword
      NEKO_TCPMUX: 8045
      NEKO_UDPMUX: 8046
      NEKO_ICELITE: 1    

Log:

10:04PM **WRN Failed to read from candidate tcp4 host correctWANipaddress:8045: io: read/write on closed pipe module=webrtc submodule=pion subsystem=ice**
2023-08-03 22:04:39,869 DEBG 'neko' stdout output:
10:04PM INF Setting new connection state: Failed module=webrtc submodule=pion subsystem=ice
10:04PM INF ICE connection state changed: failed module=webrtc submodule=pion subsystem=pc
10:04PM INF connection state has changed connection_state=failed module=webrtc
10:04PM INF peer connection state changed: failed module=webrtc submodule=pion subsystem=pc
10:04PM **WRN peer failed id=oyKKJsevpy_X9ms-hMEkq0PeVDeptq7J module=webrtc
2023-08-03 22:04:39,869 DEBG 'neko' stdout output:**
10:04PM **WRN Failed to discover mDNS candidate b8e6b99b-359a-488e-9aba-9b1d31382548.local: mDNS: connection is closed module=webrtc submodule=pion subsystem=ice**
10:04PM INF Setting new connection state: Closed module=webrtc submodule=pion subsystem=ice
10:04PM INF peer connection state changed: closed module=webrtc submodule=pion subsystem=pc
10:04PM INF ICE connection state changed: closed module=webrtc submodule=pion subsystem=pc
10:04PM INF connection state has changed connection_state=closed module=webrtc
2023-08-03 22:04:39,870 DEBG 'neko' stdout output:
10:04PM **WRN Failed to start manager: connecting canceled by caller module=webrtc submodule=pion subsystem=pc**
10:04PM INF peer closed id=oyKKJsevpy_X9ms-hMEkq0PeVDeptq7J module=webrtc
10:04PM **WRN Failed to start SCTP: DTLS not established module=webrtc submodule=pion subsystem=pc**
10:04PM **WRN undeclaredMediaProcessor failed to open SrtpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc**
10:04PM **WRN undeclaredMediaProcessor failed to open SrtcpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc**

I have my own domain address, and I use nginx proxy manager. The TCPMUX and UDPMUX port are forwarded in router.

Firefox, Chrome, Edge same error. I cannot log in. Please help.
![neko](https://github.com/m1k1o/neko/assets/47332170/8c607336-7091-47eb-b961-56626fcb5656)

**Comment by m1k1o** [comment]
Please go through troubleshooting page, this looks like network issue:
https://neko.m1k1o.net/#/getting-started/troubleshooting

Also make sure that you forward websockets properly using nginx proxy manager.

**Comment by ZsiGiT** [comment]
Hi m1k1o!

I've read through the page twice. I don't know why it doesn't work properly. What is the specific websocket port for forwarding? 

- "8045:8045/tcp"
- "8046:8046/udp" this two ports?

These are the settings for the nginx proxy manager:

![proxy 2023-08-04 210346](https://github.com/m1k1o/neko/assets/47332170/a9f2a6fb-0ded-4569-bb8d-c6ce22d460d7)
![main 2023-08-04 210248](https://github.com/m1k1o/neko/assets/47332170/0141c0ce-99cc-4e22-b8b3-30788deb2020)
![steam 2023-08-04 210429](https://github.com/m1k1o/neko/assets/47332170/96eedede-094b-4972-9bc0-41ec3440e0c2)

And router portforward:

![portforward 2023-08-04 210533](https://github.com/m1k1o/neko/assets/47332170/caef6fcc-0e23-4681-8a2a-bdf719df4770)

**I have no idea anymore.**

**Comment by m1k1o** [comment]
I havent see any problem with your configuration, it looked fine. Were you able to fix your issue? If so, could you please let us know how? Thanks.

**Comment by ZsiGiT** [comment]
That was a pretty funny mistake.

Not even neko or docker or port forward error. My ISP is telekom. I have my own domain. For example: mydomain.eu . I made an address neko.mydomain.eu. It is redirected within nginx proxy manager to neko.mydomain.eu at 192.168.10.50:8586. I can access this from another location (my friends, workplace) or via mobile internet. Everything works like this. Log in, watch a movie, chat, send a file.  But not from LAN.

I do not know why it does not work.

All other subdomain redirects work from LAN. A lot of my subdomain redirects work in docker, neko does not.

Thank you for your time.

**Comment by m1k1o** [comment]
That looks like [NAT Loopback (NAT Hairpinning)](https://neko.m1k1o.net/#/getting-started/troubleshooting?id=neko-works-externally-but-not-locally) issue. Maybe your ISP does it only for HTTPS (or TCP) and not for UDP.

Thanks for sharing!

**Comment by mbattista** [comment]
Hi,

do not blame the ISP, since Hairpinning Traffic should never leave your router. 

The first error shows a webrtc tcp broken pipe, which either means, that your connection to neko was closed or that neko could not establish a connection back to your PC. 

To debug I would do the following steps:
1. Check if you can access and logon into neko with its LAN IP Address.
2. If this does not work, change all the Ports in the neko config (and only there!) and try to connect via LAN again with the new ports.

If either of this works, reset the neko config and set the IP of your domain to your nginx server on your PCs hosts file and try again. If this also works, you should look to invest into a new router.

If neither works, then try with a different device in your LAN. It could also be the browsersetting, that hides your IP from webrtc.

In Chrome, by disabling Anonymize local IPs exposed by WebRTC in "about:flags" page. (Via https://stackoverflow.com/questions/61629450/webrtc-does-not-work-in-the-modern-browsers-when-a-peer-is-not-behind-a-nat-beca )

Further ideas I do not have right now.

**Comment by leechunyen** [comment]
I also got same issue,
I not using Nginx Proxy Manager,
I just visit the page by local IP address.

<img width="1382" alt="Screenshot 2024-03-12 at 11 44 49 PM" src="https://github.com/m1k1o/neko/assets/75829167/24fd76ec-aa8f-4879-b4b5-c514672db27d">
<img width="1382" alt="Screenshot 2024-03-12 at 11 45 04 PM" src="https://github.com/m1k1o/neko/assets/75829167/70485a97-5904-499a-985f-7d886fbee6d5">
<img width="738" alt="Screenshot 2024-03-12 at 11 46 41 PM" src="https://github.com/m1k1o/neko/assets/75829167/9009ddc9-0046-47d4-b414-350e29d928a8">

**Comment by m1k1o** [comment]
Please take a look at troubleshooting page if you haven't yet: https://neko.m1k1o.net/#/getting-started/troubleshooting

**Comment by yuuuuuuan** [comment]
> I also got same issue, I not using Nginx Proxy Manager, I just visit the page by local IP address.
> 
> 👇This is the docker-compose.yaml I use to install👇 https://raw.githubusercontent.com/m1k1o/neko/master/docker-compose.yaml
> 
> <img alt="Screenshot 2024-03-12 at 11 44 49 PM" width="1382" src="https://private-user-images.githubusercontent.com/75829167/312150676-24fd76ec-aa8f-4879-b4b5-c514672db27d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjIxMDMsIm5iZiI6MTcyMzU2MTgwMywicGF0aCI6Ii83NTgyOTE2Ny8zMTIxNTA2NzYtMjRmZDc2ZWMtYWE4Zi00ODc5LWI0YjUtYzUxNDY3MmRiMjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE1MTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YzZmNWQ5OWM4ODNlN2NmMWI5YjBhN2UwODNiYWU4ZjliNGFhMjcwOTA1NDY1Mzg5YjU0MTkxMDBlNTYzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7rszyXyzy9a4ztX0VQRwAH6-KVZxUrtZFsyTkGV7t7w"> <img alt="Screenshot 2024-03-12 at 11 45 04 PM" width="1382" src="https://private-user-images.githubusercontent.com/75829167/312150735-70485a97-5904-499a-985f-7d886fbee6d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjIxMDMsIm5iZiI6MTcyMzU2MTgwMywicGF0aCI6Ii83NTgyOTE2Ny8zMTIxNTA3MzUtNzA0ODVhOTctNTkwNC00OTlhLTk4NWYtN2Q4ODZmYmVlNmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE1MTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiOTM1OWIyNDIwZWY2MDg5ZTgyOTE2NjQxNTkzNjFhNzY3MWJhMDA4ZGNlMmYwNzFkNzA1ZjRiMmVmMGRjZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cJ5vW0LkKMk5RKOOEcyAOISxYSMQQl_OhwrgYjt8f-E"> <img alt="Screenshot 2024-03-12 at 11 46 41 PM" width="738" src="https://private-user-images.githubusercontent.com/75829167/312150766-9009ddc9-0046-47d4-b414-350e29d928a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjIxMDMsIm5iZiI6MTcyMzU2MTgwMywicGF0aCI6Ii83NTgyOTE2Ny8zMTIxNTA3NjYtOTAwOWRkYzktMDA0Ni00N2Q0LWI0MTQtMzUwZTI5ZDkyOGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE1MTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYTFkMThlYTAzZDU4ZjkyZTE3Y2U2YjA4N2U0NGNmNjc2YTI4MjAwMTI2Y2EzYWM1ZTYwNDBkMjgzNDRiMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2t6ll6WvcaewIi2YUcn9W3lV0l8gYp3UZn9QnjwXymY">

hey !!!are you resolve this quetion?i am confused too

**Comment by kuloutoussssss** [comment]
我也遇到了同样的问题，不知道怎么解决
