### ISSUE TITLE
Neko Not Starting

### ISSUE THREAD

**Issue by SOG-web** [m1k1o/neko#326]
am getting this error

`
exec /usr/bin/supervisord: exec format error
exec /usr/bin/supervisord: exec format error
exec /usr/bin/supervisord: exec format error
exec /usr/bin/supervisord: exec format error
`

Am using portainer

version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1

**Comment by m1k1o** [comment]
Do you maybe have ARM server? Or do you happen to use windows?

> On Linux servers, you can use the command 'lscpu' to view the server's processor information, including the architecture (x86_64 for Intel and aarch64 for ARM).

**Comment by SOG-web** [comment]
linux aarch64 Ubuntu 22.04.1 LTS

**Comment by SOG-web** [comment]
> lscpu

I just looked in up it ARM

**Comment by m1k1o** [comment]
There are separate images for ARM: https://neko.m1k1o.net/#/getting-started/
![image](https://github.com/m1k1o/neko/assets/7534274/ea8f0871-eb63-45d0-8f62-581f57ca2ad4)

Though people have been reporting that there is some issue with audio.
