### ISSUE TITLE
File transfer not working

### ISSUE THREAD

**Issue by CreeperSword** [m1k1o/neko#328]
I have NEKO_FILE_TRANSFER_ENABLED set to true in my docker-compose.yaml file, but in neko (logged in as admin) the menu for transferring files is not there. I have also tried formatting the flags as NEKO_FILE_TRANSFER_ENABLED : "true" (with and without quotation marks), and that doesn't work either. 
![image](https://github.com/m1k1o/neko/assets/93549710/c1f25aa5-ba97-4ff1-9b8f-f702e68bbcfe) 
![image](https://github.com/m1k1o/neko/assets/93549710/0a6212a1-82ae-4668-af83-c27fba439acc)

**Comment by m1k1o** [comment]
Please check that you have pulled latest docker image, since this functionality was added in later versions. ARM images on dockerhub are not updated anymore, so if you use these please refer to ghcr. 
![image](https://github.com/m1k1o/neko/assets/7534274/de6684c5-e57e-42bd-912a-dd6864d16601)

**Comment by CreeperSword** [comment]
I updated docker to 4.23.0, and am using windows, and the menu still does not show up.

**Comment by CreeperSword** [comment]
using the firefox image (not the ARM one)

**Comment by cedricbieder** [comment]
I got the same Problem here, also with the firefox version. I see the file logo in the header bar before the login, but afterwards, even as admin, it disappears.

**Comment by m1k1o** [comment]
@cedricbieder its `NEKO_FILE_TRANSFER_ENABLED` with the last `D`. 
https://neko.m1k1o.net/#/getting-started/configuration?id=neko_file_transfer_enabled
