### ISSUE TITLE
Using reverse proxy

### ISSUE THREAD

**Issue by robertowilliamsep** [m1k1o/neko#330]
Hi Everyone,

I'm testing Neko behind a reverse proxy setup. While I can access the login, I'm encountering issues with TURN/COTURN functionality and have failed to connect. Does anyone have comprehensive guides or tutorials that could help with this issue? Is there a limitation?

Thanks,
Roberto

**Comment by m1k1o** [comment]
There is not much in docs about this, but if you would be open to share your findings/problems with us, we could help you and based on our findings create docs page for further users.

**Comment by ralfi** [comment]
![ksnip_20230913-132711](https://github.com/m1k1o/neko/assets/294423/eb8b56cf-00cb-4cf1-8ce5-5e5a7bc0f0ba)

This is my apache reverse proxy config part and this

![ksnip_20230913-132702](https://github.com/m1k1o/neko/assets/294423/3e6e85f8-9c0a-40a2-865e-7675794ffa0a)

is the part of my docker-compose yaml for Neko.

I only use provider based virtual machines (like Hetzner) as TURN Server. Based on my experience, using Neko is only meaningful with GPU-supported hardware, as stated in the Nvidia guide part of Neko.

**Comment by robertowilliams** [comment]
> There is not much in docs about this, but if you would be open to share your findings/problems with us, we could help you and based on our findings create docs page for further users.

Thanks.

**Comment by m1k1o** [comment]
Added coturn deployment example to docs: https://neko.m1k1o.net/#/getting-started/?id=networking
