### ISSUE TITLE
Custom Application Launch

### ISSUE THREAD

**Issue by kevingarabedian** [m1k1o/neko#336]
I would like to launch a custom application, and pass params on image load for it.  I am assuming, I can use this base image.  Can you show or provide an example of where to specify the app that is launched? I will assume I can set an environment variable for my params? I am looking to make a custom Wrapped blazor or Electron app that encapsulates.  Also, Is it possible to chroot, or is this already done? 

I will dig a little deeper into the code, awesome work! Will definitely help sponsor as soon as I get some money flowing.

Appreciate and thank you in advance for any feedback!

Kevin Garabedian

**Comment by m1k1o** [comment]
Hello,

Take a look here: https://github.com/m1k1o/neko-apps

You can find multiple examples of how other apps are launched.

Hope this helps, if you have further questions feel free to ask.
