### ISSUE TITLE
IP ban on one person bans everyone

### ISSUE THREAD

**Issue by SpiderSuave** [m1k1o/neko#341]
Hi,

Doing an IP ban on just one person prevents anyone at all from logging in no matter their IP address, including administrators. They all get the ban message at the login. Anyone who then leaves the room also cannot reenter, getting the same ban message.

This was tried with several users and I tested it myself with a different IP address. A single ban just bans all addresses.

Thanks.

**Comment by m1k1o** [comment]
Do you use neko directly or behind a reverse proxy? Because if you use reverse proxy and it's not exposing the real clients IP, with each ban you actually ban the reverse proxy thus all users.

**Comment by SpiderSuave** [comment]
Hello and thank you. I'm running the app on a Linode VPS with Ubuntu 23.04 and there's no proxy setting that I know of after checking, but maybe I'm missing something. Any suggestion on what I should look for there that could be the culprit? Thanks again for your help.

**Comment by m1k1o** [comment]
You could enable debug mode and see in logs what client's IP address you see there.

**Comment by SpiderSuave** [comment]
Hello again. On the VPS I'm using, Linode, according to the tech there, apparently there's no such log file to check for IP addresses connecting, but they also assured me that IP addresses of clients should be visible to my Linode since it's not behind a NodeBalance, and should be visible to Neko. They're figuring it's something I have misconfigured in Neko that is blocking wildcard address 0.0.0.0/32. Please, can you think of anything I could check in Neko that might be causing this? Thank you for any help. Much appreciated.

**Comment by SpiderSuave** [comment]
Okay, the IP ban function is working fine using standalone Neko, but with Neko-Rooms, so the problem is in the Neko-Rooms default config.

**Comment by m1k1o** [comment]
Moved to https://github.com/m1k1o/neko-rooms/issues/107
