### ISSUE TITLE
Custom DNS Resolver

### ISSUE THREAD

**Issue by oreillygshane** [m1k1o/neko#342]
image: firefox
host: docker (on Synology) 

Hi there,

Everything on n.eko is working as expected, but I am hoping to override the DNS resolver server for n.eko only, and ignore what my network DNS lookup provider is.

Essentially I use pi.hole, and want to have n.eko act as a sort of Web Proxy running locally, that can bypass PiHole's DNS resolver sinkhole.

Most solutions mention modifying about:config, but that looks blocked with n.eko./

Does anyone have any guidance on how I would acheive this?

**Comment by m1k1o** [comment]
Docker allows you to set custom DNS:

https://docs.docker.com/network/#dns-services

Or you can create own browser policies that have specified custom DNS and mount them to the container.

https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks

**Comment by oreillygshane** [comment]
Perfect thank you @m1k1o !

I added an ENV flag for 'dns' in the Synology DSM 'Container Manager' settings but it didn't take effect, so I used Portainer's GUI to handle it.

Thanks again!
