### ISSUE TITLE
About Google Browser Your browser is managed by your organization

### ISSUE THREAD

**Issue by nfksuss** [m1k1o/neko#345]
I installed Google Chrome using Docker, but when I opened it, I was prompted that Your browser is managed by your organization. How can I remove this supervision

**Comment by m1k1o** [comment]
That means, there is [browser policy](https://support.google.com/chrome/a/answer/9037717?hl=en). You can change this policy to accomodate your needs or [completely remove](https://support.google.com/chrome/a/answer/9844476?hl=en&sjid=2410968485999174280-EU#zippy=%2Clinux).

More info in docs:
https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks

**Comment by nfksuss** [comment]
> That means, there is [browser policy](https://support.google.com/chrome/a/answer/9037717?hl=en). You can change this policy to accomodate your needs or [completely remove](https://support.google.com/chrome/a/answer/9844476?hl=en&sjid=2410968485999174280-EU#zippy=%2Clinux) (bind empty policy file/folder).
> 
> More info in docs: https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks

Could you please provide a detailed explanation of how to bind an empty policy file/folder?

**Comment by nfksuss** [comment]
Adjusting through Docker Compose

**Comment by nfksuss** [comment]
I am using the m1k1o/neko: Google chrome image package

**Comment by nfksuss** [comment]
It has been resolved. Thank you!
