### ISSUE TITLE
browser images out of date

### ISSUE THREAD

**Issue by exalented** [m1k1o/neko#346]
Chrome and tor-browser for example are out of date.
The tor browser is a problem because once it finishes it's auto update then the container effectively terminates.

**Comment by m1k1o** [comment]
All `m1k1o/neko` images are updated every week. Add `ghcr.io/m1k1o/neko` images are updated on new tag. Last tag was 26.8 so i create new tag and it will be updated.

**Comment by m1k1o** [comment]
New tag: https://github.com/m1k1o/neko/releases/tag/v2.8.10

**Comment by exalented** [comment]
Chad
