### ISSUE TITLE
Microsoft Edge docker cannot update to most recent browser release

### ISSUE THREAD

**Issue by dotborealis** [m1k1o/neko#348]
Hello, 
I use the neko docker container, but i noticed (from the browser popups) that the browser version will not go above v95, which breaks services like Spotify that require updated browser versions for DRM reasons.
Recreating the container from scratch or even rebuilding it will not solve this problem.
Looking into it, i think the issue is in the [dockerfile](https://github.com/m1k1o/neko/blob/master/.docker/microsoft-edge/Dockerfile) code

`    SRC_URL="${API_URL}$(wget -O - "${API_URL}" 2>/dev/null | sed -n 's/.*href="\([^"]*\).*/\1/p' | tail -1)"; \
`
As this link will always grab v95, even when the "[repo](https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/)" goes up to v119, currently.
I believe this error is due to Microsoft's weird page ordering.
![image](https://github.com/m1k1o/neko/assets/120049376/2c69b333-547e-4ff7-86ec-0b0e6044fc32)

From my tests, a simple ` | tail -n 3 | head -n 1)"`  instead of tail -1 is enough to grab the latest release (it works on a modified docker image i am running to resolve this problem).

I am not sure if the browser versions are meant to be "frozen" and validated between releases or not, but i hope this helps.

Thank you for your awesome work on this application.

**Comment by m1k1o** [comment]
@dotborealis thank you. Versions are meant to be the latest when creating a tag, which is then frozen.

Seems like `sort --version-sort` works better, because when eventually MS would remove version 95 it would be incorrect again.
