### ISSUE TITLE
When will new version be released, and will it be much more configurable?

### ISSUE THREAD

**Issue by SpiderSuave** [m1k1o/neko#352]
First, thank you for this app. As it is, it's already awesome.

I would just love to see a configurable version of it to change some things like chatroom appearing automatically at login without new users having to press the hamburger button and for phone users to have the display in full screen landscape that they can easily switch back and forth from while chatting, either by swiping up the full screen video to chat below or a button in the corner to switch between video/chat. Also would be nice an option to clear bans without restarting the room, and a check for duplicate names so that a guest logging in cannot use the same name of someone already in the room.

A fully configurable version of this app so that anyone hosting a watchparty could have their own custom setup would be amazing.

Thanks again.

**Comment by m1k1o** [comment]
I cannot give you any exact time now. Maybe if multiple people find this feature useful, someone might want to start a PR and i would gladly review and merge it.

**Comment by SpiderSuave** [comment]
Thank you. I'd pay you for just a tutorial on how to modify it to just change a few things:

1. Get the chatroom to appear automatically upon login rather than new users having to click the hamburger button at the top corner.

2. Chat and new entry sounds automatically turned off at login.

3. Phone users having the display in full screen landscape with a corner button that switches to left-half display/right-half chat then back to full display, so this way they can watch a movie in full screen while at any time reducing display by half to participate in chat. And also for phone in portrait mode to show top portion display with chat under.

Less important things would be size of avatars and bottom border, checking for names at login duplicating existing names in room, buttons for full screen, pip, control appearing somewhere under the display area rather than over it, and for control button to not appear for guests who don't have access to it. 

But as you can see, it's just some minor adjustments. I just wish I knew of a support site somewhere on how to modify the source code to do this so that anyone running Neko and modify it to their own liking. Thank you again and hopefully this will be possible.

**Comment by mbattista** [comment]
Your point 1 and 2 are minimal and could be done with more url parameters. I can create a PR for this over the Weekend. 

For 3, it is mobile support and I have to try how everything behaves on a mobile device. 

Your minor points are all very specific and some could break other use cases, e.g. the duplicat check and the embedding without login.

I do not understand, what you wish for in the last paragraph. You have the source code right here. You can fork it and change it however it suits you, even create your own container and use them. Are you trying to say, that the source code needs more comments or a documentation?

**Comment by SpiderSuave** [comment]
Thank you! Just 1 and 2 for now would be awesome and that's much appreciated. I host watchparties occasionally and it helps when guests have the chatroom already there rather than that requiring an extra step for them.

Often several guests are on phone and I figure that for a small device like that, a constant full screen landscape with a corner button to bring up a half chat/half display and then back to full screen is the ideal, but another option is full screen landscape with chatroom attached under it where the whole thing can be swiped up or down to watch the full display or chat under it.

The source code is beautifully commented and documented. What I mean in the last paragraph is just a problem with me personally understanding how to modify the code and I was looking for some help, but the code itself and how it's organized is fine and I can just study it a bit more to make the changes I like.

Once again thank you for your reply and I appreciate your work.

**Comment by SpiderSuave** [comment]
Any chance of just a url parameter to have the chatroom up by default and chat sounds turned off by default is much appreciated. Thanks again for your work.

**Comment by SpiderSuave** [comment]
@mbattista, I send you a million thank yous. This is much appreciated.

**Comment by SpiderSuave** [comment]
Hi. Can ?mute_chat=1 URL parameter be made to work with ?embed=1 ?
Apparently when passing ?embed=1, the ?mute_chat=1 parameter is ignored.

Also I love the flying emojis, but is it possible please to add a URL parameter to disable them that works with embed ?

Thank you as always and your work is much appreciated.

**Comment by m1k1o** [comment]
Conversation moved to https://github.com/m1k1o/neko/issues/381
