### ISSUE TITLE
How can I embed the Neko desktop into web page without login prompt coming up for viewers?

### ISSUE THREAD

**Issue by SpiderSuave** [m1k1o/neko#353]
I'm using irframe to embed the Neko xfce desktop to a webpage by putting ?embed=1 at the end of the url.

The problem is the login prompt appears for whoever visits the web page. Is there a way to make the login prompt not appear? Thanks for any help.

**Comment by yesBad** [comment]
You can use pwd & usr variables. 

aka https://neko.yep/?usr=hi&pwd=bye

**Comment by SpiderSuave** [comment]
Thank you so much. That works. Apparently I had the format wrong and also I had forgotten about "usr=" and was only using pwd. Much appreciated.

I notice the full screen button isn't working off the embed. Any idea how to fix this? It's no biggie but I was just curious. Thanks again for your help.

**Comment by mbattista** [comment]
https://stackoverflow.com/questions/15276929/how-to-make-a-video-fullscreen-when-it-is-placed-inside-an-iframe

Your iframe needs an attribute: `allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"` or more modern `allow="fullscreen *"`
For the second you can remove the star if your iframe has the same origin.

**Comment by SpiderSuave** [comment]
Thank you! Much appreciated.

**Comment by m1k1o** [comment]
Included in Frequently Asked Questions in docs.
