### ISSUE TITLE
Black screen issue on Ubuntu VM

### ISSUE THREAD

**Issue by epic-croswords** [m1k1o/neko#361]
hello team,

i need help regarding the black screen issue while using neko on Ubuntu virtual machine i only able to see the cursor and neko currently working on docker container 

docker file: google chrome ( .docker/google-chrome)

thanks.

![image](https://github.com/m1k1o/neko/assets/138249606/88469e8d-c617-4827-a142-c2d836e5c153)

![image](https://github.com/m1k1o/neko/assets/138249606/4955660e-66d8-4439-84b2-bd11bfa34936)

**Comment by yesBad** [comment]
Did you set
```
    cap_add:
      - SYS_ADMIN
```
as per documentation?

**Comment by epic-croswords** [comment]
no i haven't set that, is it on docker file ? or where should i have to add

**Comment by yesBad** [comment]
> no i haven't set that, is it on docker file ? or where should i have to add

You set it when you launch the container i.e docker run command or compose file.

**Comment by epic-croswords** [comment]
it able to work thanks you very much  


![image](https://github.com/m1k1o/neko/assets/138249606/4ae11405-ecc1-4dbd-a86e-7ddff2b09c00)

**Comment by yesBad** [comment]
Goodluck. You can close the issue 👍
