### ISSUE TITLE
Feature: User activity

### ISSUE THREAD

**Issue by Kamukage3e** [m1k1o/neko#363]
Currently neko has the latest user activity, but in a real production environment another feature like user activity is required. Most users will forget to close the tab and leave the session open. In this situation, user activity is required. Neko will track user activity. If the user does not move the mouse or perform any action for 15 minutes, neko-rooms will automatically delete that room.
Is it possible to track ?
Ps. I tried to track via websocket but unfortunately I couldn't find any solution .

**Comment by m1k1o** [comment]
We could track the last timestamp when the cursor on the remote screen is moved (webrtc messages) but this could delete your room when you are watching something since there is no interaction.

We could track document focus/blur and send it to websockets to know when user actually is on the page and when its only open in the background on a different tab. But this would not solve the issue when users leave open room and the tab focused.

Or simply adding some timeout to the room, like max age. And the room would be stopped when exceeding that value.

**Comment by Kamukage3e** [comment]
We want to enable this feature via env like. NEKO_ACTIVITY_TIMEOUT = int. (default = 15 minutes)
But I don't know can I handle webrtc messages. Could you give me some guide  ?  Maybe I will do that feature and this feature helps to save some resource in Production environment

**Comment by Kamukage3e** [comment]
I almost finished k8s operator based kubebuilder with gin alternative version of neko rooms and I want to enable NEKO_ACTIVITY_TIMEOUT = int on neko side like metric then handle via k8s operator.

**Comment by Kamukage3e** [comment]
@m1k1o Could you give me some guide ?

**Comment by mbattista** [comment]
Can you please elaborate why you would need this?

Tracking mouse and even thinking about a default of 15 minutes sounds both horrible for a lot of usecases.

**Comment by yesBad** [comment]
> Can you please elaborate why you would need this?
> 
> Tracking mouse and even thinking about a default of 15 minutes sounds both horrible for a lot of use cases.

I agree completely, like watching a presentation/video/movie. In most cases the users are just AFK watching what is happening on the screen.

**Comment by Kamukage3e** [comment]
> Can you please elaborate why you would need this?
> 
> Tracking mouse and even thinking about a default of 15 minutes sounds both horrible for a lot of usecases.

Especially when the client will use a blog on the site to read and forgot to close the tab or log out.  It will reduce resource consumption. Especially in banks and other fields

**Comment by Kamukage3e** [comment]
return types.Stats{
        Connections: atomic.LoadUint32(&ws.conns),
        Host:        host,
        Members:     ws.sessions.Members(),

        Banned: ws.state.AllBanned(),
        Locked: ws.state.AllLocked(),

        ServerStartedAt: ws.serverStartedAt,
        LastAdminLeftAt: ws.lastAdminLeftAt,
        LastUserLeftAt:  ws.lastUserLeftAt,
        LastActivityTime: ws.webrtc.GetUserLastActivity(),    // Any activity client side mouse or keyboard

        ControlProtection: ws.conf.ControlProtection,
        ImplicitControl:   ws.webrtc.ImplicitControl(),
    }
    I will push new metric later to git repo. This metric helps to track user activity
