### ISSUE TITLE
Where is the clipboard button for Firefox-browsers?

### ISSUE THREAD

**Issue by rubydotexe** [m1k1o/neko#373]
Potentially dumb question alert

According to documentation, 
> If your browser does not support clipboard sharing:
> Clipboard icon in the bottom right corner will be displayed for host

However, when I use neko in Firefox, I do not see this clipboard: 
![image](https://github.com/m1k1o/neko/assets/52940751/b3daa31d-474e-420a-b299-63602ae010e5)

Is this feature still there?

**Comment by m1k1o** [comment]
Tested on firefox now. Is visinle when you are hosting - keyboard is active:
![image](https://github.com/m1k1o/neko/assets/7534274/9ed5c986-f732-45b0-94f2-827181986c1c)

Shown in the corner, but inside the screen area (such as fullscreen button and resolution button):
![image](https://github.com/m1k1o/neko/assets/7534274/016fd6e4-d866-4d41-957f-8a459e233656)

**Comment by m1k1o** [comment]
Probably bulletproof solution would be to show clipboard button all the time. No matter if the browser supports clipboard or no.

**Comment by m1k1o** [comment]
I can reproduce it now with Mozilla Firefox 126.0.1. Getting true for `'clipboard' in navigator && typeof navigator.clipboard.writeText === 'function'`. But the clipboard is obviously not working.

Everytime i move with my cursor to the canvas and click I get this error, which blocks the mouse event and I need to click again to have my interaction registered.
![image](https://github.com/m1k1o/neko/assets/7534274/f381a03d-b033-4ecc-bc84-4c8b0c9b9c9c)
