### ISSUE TITLE
I cannot control anything !

### ISSUE THREAD

**Issue by DarkXero-dev** [m1k1o/neko#396]
I followed guide but now I can access instance and login yet no matter what I do I cannot get it to work like mouse n keyboard do nothing all I can do is send emotes..

**Comment by m1k1o** [comment]
Were you able to grab control or is that button not working? 

Before:
![image](https://github.com/m1k1o/neko/assets/7534274/2494a226-c285-45ce-b147-3453d7087caa)

After:
![image](https://github.com/m1k1o/neko/assets/7534274/7940a595-3f33-4b73-af0f-9886e38421a4)

You should see it in the right sidebar:
![image](https://github.com/m1k1o/neko/assets/7534274/b8cf9815-c95a-425b-878a-c54e68aca3c4)

And as well in top left cornet.
![image](https://github.com/m1k1o/neko/assets/7534274/ae215310-334d-459b-ac9f-614e253182bb)

**Comment by DarkXero-dev** [comment]
That button is greyed out no matter what I do..

**Comment by DarkXero-dev** [comment]
@m1k1o I figured it out. Needed to click on the icon first. Wasn't clear in documentation. Anyway thanks.
