### ISSUE TITLE
[Feature] Add environment variable to configure Timezone

### ISSUE THREAD

**Issue by jameskitt616** [m1k1o/neko#397]
It would be a nice to have to be able to configure the Timezone inside the docker container.
I currently need to manually run `unlink /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime` inside the docker container after it successfully started.

**Comment by m1k1o** [comment]
You could do it by adding TZ Environment variable. That is a feature of debian in docker.

TZ=Europe/Vienna

**Comment by jameskitt616** [comment]
Oh thanks. Marked solved.
