### ISSUE TITLE
Option to disable auto broadcast if NEKO_BROADCAST_URL is set.

### ISSUE THREAD

**Issue by jameskitt616** [m1k1o/neko#398]
It be awesome to if there was a way to disable the automatic broadcasting on container startup if `NEKO_BROADCAST_URL` is set. This eats unnecessary resources when starting the container but no stream is needed.
It could be configured via env variable.

**Comment by m1k1o** [comment]
That option was added to automatically start broadcast. Not setting it would not start any broadcast. But you would like to see the URL pre-filled? Maybe just read-only? What is the use-case or motivation behind this?

**Comment by jameskitt616** [comment]
I often do movie nights with friends who just watch via Browser on Desktop. But like once a week we do a movie night in VrChat, which requires me to enable the stream only for this use case. So it would be nice if i could just enable the stream when i need it. And not turn it off everytime i reboot the container/VM cuz it consumes a lot of resources.

**Comment by m1k1o** [comment]
You could specify the broadcast URL only in the GUI. But I assume you would like to have that field pre-filled and do not want to enter the URL everytime you want to broadcast?

![image](https://github.com/m1k1o/neko/assets/7534274/d72fcd75-01d5-424d-a53c-acc2dda16039)

**Comment by jameskitt616** [comment]
Yes correct. I want the URL pre-filled but the broadcast not started automatically on container start.

**Comment by jameskitt616** [comment]
Alternatively i just had the idea to add an env variable to set a time like this: `BROADCAST_DISABLE_EMTPTY_ROOM_TIMEOUT=5m`
Which disables the Broadcast automatically when no one is in the neko room present for more than the given time. (default ofc disabled)

**Comment by m1k1o** [comment]
That could definitely be a topic for v3 rewrite. To make more options for broadcast (e.g. specify multiple broadcast targets and user could just select one in GUI, or entirely remove posibility to modify broadcast url, automatically starting / stopping broadcast).

But for now, adding `NEKO_BROADCAST_AUTOSTART` could be done easily, because there is already option for that in the boradcast manager.

**Comment by m1k1o** [comment]
Implemented in the last commit. You would need to use `NEKO_BROADCAST_AUTOSTART: "false"` because `true` is currently the default behavior, to keep backward compatibility.

**Comment by m1k1o** [comment]
You can create new issue, i will close this one.
