### ISSUE TITLE
[HELP] Simply stream a PID

### ISSUE THREAD

**Issue by NN-Binary** [m1k1o/neko#404]
Hi,

I have already running PIDs (aka chrome instances), I would like to use Neko to stream them, the programs are already running, not in Docker.

How can I achieve that?

**Comment by m1k1o** [comment]
You would need to share more details about your setup.

**Comment by NN-Binary** [comment]
Actually, the setup can be remade anytime, right now it runs Xubuntu (locally, not via SSH or remotely), I wish to access from a browser any PID I wish dynamically.
