### ISSUE TITLE
Emojis are broken

### ISSUE THREAD

**Issue by m1k1o** [m1k1o/neko#41]
![image](https://user-images.githubusercontent.com/7534274/113489879-1106e780-94c7-11eb-8ac2-d00b710eca6a.png)

**Comment by m1k1o** [comment]
Might have been broken by afbd1f6f590cb75778260737e8fc7e82352ddff0, because no recent major changes have been done. @mbattista.

**Comment by m1k1o** [comment]
emoji-datasource has been upgraded to new major version, what can cause problems:

https://github.com/m1k1o/neko/commit/b88f1750f7d57a546cb73a2e253607bc44c61a83#diff-1846122c2c83a486a3693f7966aa522c34cf489f674185c4da0d9221683fd81fR27

**Comment by mbattista** [comment]
I will look at it

**Comment by m1k1o** [comment]
I already figured out the solution. They changed row cont from 57 to 58.

https://github.com/m1k1o/neko/blob/e27b98d509d8b9999b04823e16524610d0ed8cbb/client/tools/emoji.ts#L53

It would be nice to have this as variable from the package, insted of just a constant.

**Comment by m1k1o** [comment]
It looks like, now the names are not correct.

![image](https://user-images.githubusercontent.com/7534274/113511213-08fa8680-955f-11eb-8844-efdb32a081e8.png)

**Comment by mbattista** [comment]
It seems the downgrade was not necessary if I bump it again, the emojis still look good.

Also I think that fixing with downgrading should never close an issue, since the problem is still there!

**Comment by m1k1o** [comment]
You are right, that just postpones it.

Upgrading `emojilib` to new major version has many beaking changes, listed here: https://www.npmjs.com/package/emojilib

Since emojis are generated statically, you need to run `npm run build:emoji`  to regenerate them. With new version you get ton of erros, because it has been completly changed. That might need complete rewrite.
