### ISSUE TITLE
Why can't we share files anymore?

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko#417]
![1724980885331](https://github.com/user-attachments/assets/256f2aec-544a-4cfb-a84e-55c8f5f38f2c)
but the old version look like this
![1724981004958](https://github.com/user-attachments/assets/d132fc67-aeb9-470d-b5c4-b8e470c3e996)

**Comment by m1k1o** [comment]
Which old/new version? What code are you testing?

**Comment by m1k1o** [comment]
Probably just not enabled in environment variables, by default it is false.

**Comment by z2labplus** [comment]
I set the environment variables
NEKO_FILE_TRANSFER：true
NEKO_FILE_TRANSFER_PATH：/root
but it still working
any mistake I take？
