### ISSUE TITLE
Can I upload pictures to the browser in one step?

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko#418]
![1725038565787](https://github.com/user-attachments/assets/5bc96486-15a3-4ebb-82cd-c0f0e7722bd2)
Now I can upload the photo to chromium,but I need 2 step.
can I finished in one step?

**Comment by m1k1o** [comment]
That would require Integration with google chrome API or Gtk Chooser Dialog API. I am not sure how that could be done.

**Comment by z2labplus** [comment]
thanks
