### ISSUE TITLE
Extend desktop width/height a bit to fill in margin on sides

### ISSUE THREAD

**Issue by SpiderSuave** [m1k1o/neko#421]
Hi. There's a bit of a margin on the sides of the desktop I'd like to fill in by extending width and height including reducing height of bottom where avatars go. Could you please give a tip on what values in .vue files (or wherever else) to edit?

I've been editing values in the resolution.vue and video.vue files, recompiling and by trial and error been able to change the size but it's not exactly working like I want because I'm not sure of exactly what values to change.

Any help is much appreciated. Thank you.

**Comment by m1k1o** [comment]
Duplicate https://github.com/m1k1o/neko/issues/426.

You should be able to control the values here: https://github.com/m1k1o/neko/blob/2cd4957472ce9439cec8bf95b527e4eb9d12fec4/client/src/assets/styles/_variables.scss#L27-L29
