### ISSUE TITLE
Why is developer mode not supported，Is there any way to not disable it

### ISSUE THREAD

**Issue by javascriptNode** [m1k1o/neko#428]
![exmple](https://github.com/user-attachments/assets/3be9c4c9-ad91-48b3-9938-f3fc5a7f1572)

**Comment by m1k1o** [comment]
It's because of security, it can be enabled in the policy file.

**Comment by javascriptNode** [comment]
> 这是出于安全考虑，可以在策略文件中启用它。https: [//neko.m1k1o.net/#/getting-started/ ?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks](https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks)

非常感谢

**Comment by javascriptNode** [comment]
> It's because of security, it can be enabled in the policy file. https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks

Thank you very much
