### ISSUE TITLE
Upload 413 error

### ISSUE THREAD

**Issue by maheshrana2002** [m1k1o/neko#430]
How to upload file more than or equal to 100mb size 
![image](https://github.com/user-attachments/assets/661fe67e-e03e-4672-b8e6-9e89ae9a00e6)
I have even mount the path of my server for the location

**Comment by m1k1o** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413

Do you happen to have any proxy server in between? Or is this error coming directly from neko?

**Comment by maheshrana2002** [comment]
I was able to fix the issue actually its an cloudflare issue ,Thanks for replying btw
