### ISSUE TITLE
How to set browser startup to mobile mode

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko#436]
![1729586485456](https://github.com/user-attachments/assets/bae6b2ed-e219-4f30-a546-ea510a7936bc)

How to set browser startup to mobile mode
Which file?   @m1k1o 
Thanks very much!

**Comment by z2labplus** [comment]
???  @m1k1o

**Comment by m1k1o** [comment]
Hello. I don't know what you are exactly trying to do. We don't have any specific mobile mode.

**Comment by z2labplus** [comment]
![1729693849443](https://github.com/user-attachments/assets/f6c1b24e-f842-47a9-ba0c-dcb7889eeff8)
Like the Chrome F12 develop mode,clicke the mobile,then  show the mobile style.

**Comment by m1k1o** [comment]
It's still unclear to me. Neko uses fluid frontend layout that can fit into many screens. There is no specific mobile mode.
