### ISSUE TITLE
When I modify the code,how to build a new docker image,and how to use the docker-compose.yaml?

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko#439]
When I modify the code,how to build a new docker image,and how to use the docker-compose.yaml?

**Comment by yesBad** [comment]
https://github.com/m1k1o/neko/blob/master/.docker/README.md
https://docs.docker.com/compose/intro/compose-application-model/

**Comment by z2labplus** [comment]
yes , after modify the code,I run the command 
cd .docker
./start-server
./serve-client
to verify the code and function,
but how to build a image and then run with docker-compose.yaml in a new machine?

**Comment by z2labplus** [comment]
Maybe I didn't express myself too clearly
how to build a image image: "m1k1o/neko:firefox" after I modify the code
when I can run withe the https://github.com/m1k1o/neko/blob/master/docker-compose.yaml

**Comment by m1k1o** [comment]
With ./build base and ./build firefox

**Comment by z2labplus** [comment]
aftet I run the command ./build firefox,
I get a image 
m1k1o/neko   firefox   5496e2fcbd9b   6 seconds ago   1.08GB
Does this image include the code I have modified?
@m1k1o

**Comment by m1k1o** [comment]
Only if you first did also the build base command.

**Comment by z2labplus** [comment]
> Only if you first did also the build base command.
thanks
so I need to two command
./build base   
and
./build firefox  ?

**Comment by m1k1o** [comment]
> With `./build base` and `./build firefox`.

Yes, as stated above.

**Comment by z2labplus** [comment]
thanks
so I need to two command
./build base   
and
./build firefox  ?

and when I push the image 
m1k1o/neko firefox 5496e2fcbd9b 6 seconds ago 1.08GB
to the another machine, it raise the error

**Comment by m1k1o** [comment]
You cannot push the image because you don't have permissions to modify it. You can retag it e.g. `docker tag m1k1o/neko:firefox your-username/neko:firefox` and push it to your own registry.
