### ISSUE TITLE
Docker labs crashes any fix? https://labs.play-with-docker.com/

### ISSUE THREAD

**Issue by Undertaker-afk** [m1k1o/neko#440]
I tried this script 
Docker run ghcr.io/m1k1o/neko/intel-tor-browser:sha-11a862f101355ce400c81e56f3b37d1d94523542

But my docker playground instance gets termineted and deleted any idea on how to fix it

**Comment by yesBad** [comment]
I suggest asking them.

**Comment by yesBad** [comment]
Correct.

Neko has nothing to do with them, ask them if you're having issues.

**Comment by Undertaker-afk** [comment]
I know but maybe it has something to do with the nature of neko thats why i was asking here

**Comment by m1k1o** [comment]
Most likely they restrict CPU and RAM resources usage so the browser cannot run properly. And if it tries to use these resources it is OOM and get deleted.
