### ISSUE TITLE
Can I Kick or Ban someone from the room through the API?

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko#441]
Can I Kick or Ban someone from the room through the API?
or
Can I make someone in the room lose control through an API?
![image](https://github.com/user-attachments/assets/887de4ae-f97a-45ac-9a0c-7dbec6ffb097)

**Comment by m1k1o** [comment]
In v3 [yes](https://github.com/m1k1o/neko/blob/a569f720879cd2535c9cef9e3db882068e0a9802/server/openapi.yaml#L214) and [yes](https://github.com/m1k1o/neko/blob/a569f720879cd2535c9cef9e3db882068e0a9802/server/openapi.yaml#L541), it will be possible. For current implementation not easily, you would need to connect to websocket as another user.

**Comment by z2labplus** [comment]
in the neko v3 or neko-rooms v3 ? and the v3 is release?

**Comment by m1k1o** [comment]
In neko v3, neko rooms works with both. Its on the v3 branch.

**Comment by z2labplus** [comment]
Thanks very much!
Can we add users through APIs? Delete user? ban user ?

**Comment by m1k1o** [comment]
In v3 yes. You can copy the openapi.yaml to some editor like https://swagger.io and it shows you interactively what APIs are available.

**Comment by z2labplus** [comment]
I use the https://app.swaggerhub.com/apis/Z858570636/n-eko_rest_api/1.0.0#/members/membersCreate
![1731893751261](https://github.com/user-attachments/assets/31d881e5-9a8b-42c9-b443-902478ff466f)
but it show the error
{
  "code": 401,
  "message": "Unauthorized"
}
how to add the token

**Comment by m1k1o** [comment]
You need to perform login, one of the first api calls. And then there is probably possibly to set the token in swagger. https://stackoverflow.com/questions/32910065/how-to-use-authorization-bearer-token-in-a-swagger-spec

**Comment by z2labplus** [comment]
I use the  /api/login 
![1731922530245](https://github.com/user-attachments/assets/aaec8704-c19d-49f5-bdd5-d1204af61df9)
and then get the response 
![1731922555137](https://github.com/user-attachments/assets/64417af4-36e2-4614-8a30-5abfec96ffd6)
and then use the token
{
  "id": "admin-tRjjT",
  "token": "VBPykToh-HpB7Yuw-gDRMkoutYmatJriI-IC6BE9iqmy3Bs6sM8lhRTbI83CdoRs",
  "profile": {
    "name": "admin",
    "is_admin": false,
    "can_login": true,
    "can_connect": true,
    "can_watch": true,
    "can_host": true,
    "can_share_media": true,
    "can_access_clipboard": true,
    "sends_inactive_cursor": true,
    "can_see_inactive_cursors": false,
    "plugins": null
  },
  "state": {
    "is_connected": false,
    "is_watching": false
  }
}
and then use the 
![1731922625128](https://github.com/user-attachments/assets/21dfa65d-86df-49f3-afc5-d56eb2a96510)
import requests

url = "http://74.48.86.124:3000/api/members"

token = "VBPykToh-HpB7Yuw-gDRMkoutYmatJriI-IC6BE9iqmy3Bs6sM8lhRTbI83CdoRs"
headers = {
    "Authorization": f"Bearer {token}"
}

data = {
  "username": "admin",
  "password": "neko",
  "profile": {
    "name": "bill",
    "is_admin": False,
    "can_login": True,
    "can_connect": True,
    "can_watch": True,
    "can_host": True,
    "can_share_media": True,
    "can_access_clipboard": True,
    "sends_inactive_cursor": True,
    "can_see_inactive_cursors": True,
    "plugins": {
      "additionalProp1": {}
    }
  }
}
response = requests.post(url, headers=headers, json=data)

print(response.status_code)
print(response.text)
but I get the result 
![1731922678543](https://github.com/user-attachments/assets/36934982-8a6b-45c1-9c70-e1f3450ff47c)
403
{"code":403,"message":"session is not admin"}
I say  the admin account not the admin, another account ? how to solve it ?

**Comment by m1k1o** [comment]
As you can see in your details, the user is not admin, so he cannot list members.
![image](https://github.com/user-attachments/assets/f9b887dd-345e-4edc-bbc2-c9e689cebd58)

By default the login is done the same way as in the neko v2, where you have a single password for admin and a single password for user. When you use this password it creates a new profile based on that. It looks like you used password `neko` that is probably assigned to user profile. Even though you used username `admin` its just a display name that can be anything. Try using the adming password.

**Comment by z2labplus** [comment]
I use the 
username:admin
password:admin
to get the token
and send the request

import requests

url = "http://74.48.86.124:3000/api/members"

token = "nzw_3LufSXeiUQeOunmpjwo71L3smIp8qql6Q208yMk_OhgMH0z2sGaXGRgTougk"
headers = {
    "Authorization": f"Bearer {token}"
}

data = {
  "username": "user2",
  "password": "password2",
  "profile": {
    "name": "bill2",
    "is_admin": True,
    "can_login": True,
    "can_connect": True,
    "can_watch": True,
    "can_host": True,
    "can_share_media": True,
    "can_access_clipboard": True,
    "sends_inactive_cursor": True,
    "can_see_inactive_cursors": True,
    "plugins": {
      "additionalProp1": {}
    }
  }
}
response = requests.post(url, headers=headers, json=data)

print(response.status_code)
print(response.text)

but it still can not to create the new user,it raise the error 
 **ERR request failed (500): Internal Server Error error="new user is created on first login in multiuser mode"** 
how to solve it?

**Comment by m1k1o** [comment]
By default, there is multiuser mode meaning that new users are created when logging in. You can switch to other user mode and then you need to create your own users.

Add this to env:
```env
NEKO_SESSION_API_TOKEN="yourApiTokenCanBeAnything"
NEKO_MEMBER_PROVIDER="object"
```

You will now need to create your own users and you can delete/manage them. By default you will have no users when starting neko, and you can use the specified access token to create these users.

**Comment by z2labplus** [comment]
add this
NEKO_SESSION_API_TOKEN="yourApiTokenCanBeAnything"
NEKO_MEMBER_PROVIDER="object"
to the .docker/.env.default file ?

**Comment by m1k1o** [comment]
If you use dev scripts then you need to directly modify start script. You will see there are other environment variables and you need to add it to them.

**Comment by z2labplus** [comment]
I motify the file server/dev/start
![1732022793563](https://github.com/user-attachments/assets/ee83527d-feab-4733-a8db-651979b335c4)
and run the server/dev/start
and I request again,it also show me the error 
**_new user is created on first login in noauth mode"_**

**Comment by z2labplus** [comment]
it works,thanks a lot!
