### ISSUE TITLE
upload the file 403 in v3

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko#451]
I modify the v3's neko/server/dev/start
![1732683728955](https://github.com/user-attachments/assets/e6f66688-ab7d-4532-8f08-b23c25d1eea9)
and then I upload the file 
![1732683766986](https://github.com/user-attachments/assets/ec234ce8-8bdb-4070-ad45-ed9a47467ada)
it raise the error 
2024-11-27 05:03:53,203 DEBG 'neko' stdout output:
5:03AM WRN request failed (401): Unauthorized error="member does not exist" module=http req={"agent":"Go-http-client/1.1","id":"ac9b7bea8bf8/7YFYHftBfH-000207","method":"POST","proto":"HTTP/1.1","remote":"127.0.0.1:52532","scheme":"http","uri":"http://127.0.0.1:8080/api/login"} res={"bytes":38,"elapsed":0.053815,"status":401,"time":"Wed, 27 Nov 2024 05:03:53 UTC"}

2024-11-27 05:03:53,204 DEBG 'neko' stdout output:
5:03AM WRN request failed (403): error response from backend: Unauthorized module=http req={"agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","id":"ac9b7bea8bf8/7YFYHftBfH-000206","method":"POST","proto":"HTTP/1.1","remote":"74.48.86.124:38930","scheme":"http","uri":"http://74.48.86.124:3000/file?pwd=password2"} res={"bytes":67,"elapsed":0.502868,"status":403,"time":"Wed, 27 Nov 2024 05:03:53 UTC"}

how to solve it?

**Comment by z2labplus** [comment]
Does this mean that I need to redo this code myself?

**Comment by m1k1o** [comment]
Since you use a different authentication not the legacy you just need to add proper Authorization header instead of ?pwd. So it should not be a big change.

**Comment by z2labplus** [comment]
So I  just need to use the
NEKO_SESSION_API_TOKEN=yourApiTokenCanBeAnything to authorization 
to post the file?

**Comment by z2labplus** [comment]
I modify the function in server\internal\http\legacy\handler.go
	r.Post("/file", func(w http.ResponseWriter, r *http.Request) error {
		// 检查认证
		password := r.URL.Query().Get("pwd")
		if password != "admin" {
			return fmt.Errorf("unauthorized access")
		}

		// 检查Content-Type
		contentType := r.Header.Get("Content-Type")
		if !strings.Contains(contentType, "multipart/form-data") {
			return fmt.Errorf("invalid content type: must be multipart/form-data")
		}

		// 设置最大文件大小限制 (10MB)
		if err := r.ParseMultipartForm(10 << 20); err != nil {
			return fmt.Errorf("error parsing form: %v", err)
		}

		// 获取上传的文件
		file, handler, err := r.FormFile("files")
		if err != nil {
			return fmt.Errorf("error retrieving file: please ensure a file is included in the request with field name 'file'")
		}
		defer file.Close()

		// 验证文件名不为空
		if handler.Filename == "" {
			return fmt.Errorf("invalid filename")
		}

		// 创建上传目录（如果不存在）
		uploadDir := "/home/neko/Downloads"
		if err := os.MkdirAll(uploadDir, 0755); err != nil {
			return fmt.Errorf("error creating upload directory: %v", err)
		}

		// 创建带时间戳的文件名以避免冲突
		timestamp := time.Now().Format("20060102150405")
		filename := fmt.Sprintf("%s_%s", timestamp, handler.Filename)
		dst, err := os.Create(filepath.Join(uploadDir, filename))
		if err != nil {
			return fmt.Errorf("error creating destination file: %v", err)
		}
		defer dst.Close()

		// 复制文件内容
		if _, err := io.Copy(dst, file); err != nil {
			return fmt.Errorf("error copying file: %v", err)
		}

		// 返回成功响应
		w.Header().Set("Content-Type", "application/json")
		response := map[string]interface{}{
			"success": true,
			"message": "File uploaded successfully",
			"filename": filename,
		}
		return json.NewEncoder(w).Encode(response)
	})
and it works 
![1733453965435](https://github.com/user-attachments/assets/e07a502f-1e30-4127-aab3-935c183abb67)

thanks very much
