### ISSUE TITLE
Can I  display the Chat button

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko#454]
![1733740482630](https://github.com/user-attachments/assets/d85bc60a-f347-4f4f-ae0a-63bed316b549)
any parameter  can make the Chat button not show
or I need to modify the source code?

**Comment by z2labplus** [comment]
![1733790739519](https://github.com/user-attachments/assets/8f2a8849-c512-40fb-8ddb-204ca0967f5f)
Just solve use the mothed modify the code.
I don't know if there are other better methods?

**Comment by m1k1o** [comment]
No, currently no other method available. Such advanced customizations must be done in code.
