### ISSUE TITLE
Handle better reconnects

### ISSUE THREAD

**Issue by m1k1o** [m1k1o/neko#48]
Reconnects are annoying. It happens often with weak/instable connections. After reconnect it works again, however, when watching video you miss 3 - 6 seconds.

Reconnects should be better understood, why they happen and what could be done to prevent them. Since I watch video without any visible problems, and after reconnect that video works again, network must be good enough. Maybe some timers are there, that expire or kick user out in some weird edge case scenarios.

Temporary network problems should be handled gracefully. If possible (in Pion).

**Comment by m1k1o** [comment]
To simulate bad network conditions, this command can be used:

```
tc qdisc add dev eth0 root netem delay 200ms 330ms 22.00% distribution paretonormal loss 18.00% 30.00% corrupt 32.00% 88.00% duplicate 14.00% 55.00% reorder 63.00% 44.00% gap 55
```

**Comment by mbattista** [comment]
The only timer I could think of would be the websocket after 5 seconds.

So you have any console and neko logs of a disconnect?

**Comment by m1k1o** [comment]
The logs do not say anything at all. Nor on client or on server (even with debug on). Just that peer connection closed.

Websocket is fine, only WebRTC seems to fail. But if that disconnects, then also websocket is reconnected.

I've been thinking about implementing [ICE Restart](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Session_lifetime#ice_restart) (new in pion v3), maybe that could help.

**Comment by m1k1o** [comment]
Testing for some months, number of reconnects dropped to almost zero. Considering this issue as fixed.
