### ISSUE TITLE
[Feature] Add a way to translate this awesome repo

### ISSUE THREAD

**Issue by RisedSky** [m1k1o/neko#52]
Can you add a way to translate it ? i'm french and i'd like to translate the repo
You can use Crowdin if you want

**Comment by comradekingu** [comment]
Happy to help if you use Weblate or any other libre service or platform :)

**Comment by mbattista** [comment]
Sorry, I am confused what exactly you want to translate?

If you want to add translations to the frontend, there is already an option to do that. As an example: https://github.com/m1k1o/neko/pull/42/files

**Comment by comradekingu** [comment]
@mbattista Yes, but in a more user-friendly way.
Had a go in #54

**Comment by m1k1o** [comment]
There is not much text to translate in this project anyway, and I think having it in files without any 3rd party providers is sufficient for now. If thisproject grows in terms of code and popularity, then it can be considered.

**Comment by RisedSky** [comment]
I'm closing this issue, as i did a PR to translate into French :)
