### ISSUE TITLE
[Lowest priority] Chromium not working properly

### ISSUE THREAD

**Issue by RisedSky** [m1k1o/neko#64]
Getting the WebRTC, tried with Firefox, working well, changed to Chromium, not working : 
![image](https://user-images.githubusercontent.com/23197999/120025033-5c81d180-bff0-11eb-8397-07e199e6a5b4.png)

Working with Ungoogled-chromium, so i assume the chromium one is having some issue,
Do you need some log files ?

(Also, when will you release in the stable branch the french i18n ? :smile: )

**Comment by m1k1o** [comment]
I just used fresh chromium and it works for me. There was already an issue, where chromium did not work for someone, because a dependency `chromium-sandbox` was missing. Srangely, I am not able to reproduce that issue and that container simply works for me.

If you can provide logs, that would be good. If that problem is with missing `chromium-sandbox`, then I'll push that fix.

> Also, when will you release in the stable branch the french i18n ?

Dev branch is our stable/main branch. That name is misleading, and it should be changed soon. Though I hope, that this fork gets merged once to the upstream repository.

It is already available here, maybe you don't have up-to-date image. Try to pull it again.

![image](https://user-images.githubusercontent.com/7534274/120032262-382af280-bffa-11eb-9249-52e30cfe51cb.png)

**Comment by RisedSky** [comment]
> I just used fresh chromium and it works for me. There was already an issue, where chromium did not work for someone, because a dependency `chromium-sandbox` was missing. Srangely, I am not able to reproduce that issue and that container simply works for me.
> 
> If you can provide logs, that would be good. If that problem is with missing `chromium-sandbox`, then I'll push that fix.
> 
> > Also, when will you release in the stable branch the french i18n ?
> 
> Dev branch is our stable/main branch. That name is misleading, and it should be changed soon. Though I hope, that this fork gets merged once to the upstream repository.
> 
> It is already available here, maybe you don't have up-to-date image. Try to pull it again.
> 
> ![image](https://user-images.githubusercontent.com/7534274/120032262-382af280-bffa-11eb-9249-52e30cfe51cb.png)

french is working perfectly, i'll send you logs when i have time to

**Comment by m1k1o** [comment]
This should be already fixed, @RisedSky can you please try it again with new images?

**Comment by RisedSky** [comment]
Tried "google-chrome", working correctly
Tried "chromium", still not working

How can i provide logs ? (i don't like to use docker, and don't know exactly how to use it, as it prefer using proxmox and etc..)

**Comment by m1k1o** [comment]
Interesing, that is weird. You can get chromium logs from `/var/log/neko/chromium.log`. So you can copy that file from the container to your host using `docker cp neko_conainer_name:/var/log/neko/chromium.log chromium.log`.

**Comment by RisedSky** [comment]
`root@debian-ptero:~/neko# cat chromium.log

[86:86:0610/202921.764467:ERROR:zygote_host_impl_linux.cc(117)] No usable sandbox! If this is a Debian system, please install the chromium-sandbox package to solve this problem. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.`

**Comment by m1k1o** [comment]
Didn't you forget to pull `docker pull m1k1o/neko:chromium` latest image? Because exactly this issue i was addressing and installing `chromium-sandbox` package earlier. If not, then I don't know what more I can do here.

**Comment by RisedSky** [comment]
Alright, yeah, forgot to pull the new image, didn't know it was needed to !
Working perfectly now !
![image](https://user-images.githubusercontent.com/23197999/121596783-33c1f900-ca40-11eb-90a2-fdc93eeb0229.png)

**Comment by RisedSky** [comment]
I close this issue as it's not happening anymore with the newest version.
