### ISSUE TITLE
No clipboard

### ISSUE THREAD

**Issue by SenpaiBox** [m1k1o/neko#75]
So I have the container succesfully reverse proxy using "Swag/Cloudflare" and I am able to access it at its subdomain "neko.my.domain" and everything works except the clipboard. At first login it does ask for clipboard permission and I allow but it still does not show up only if I access it with internal ip and port.

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name neko.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app 10.1.3.10;
        set $upstream_port 6530;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
}
```

**Comment by m1k1o** [comment]
Do you mean that clipboard icon on the right? That is shown only as fallback. If you accept clipboard permission you can just copy and pase seamlessly to neko. Although, there is already [a request](https://github.com/nurdism/neko/pull/95#issuecomment-657283717) to have it available all the time.

**Comment by SenpaiBox** [comment]
OH! I feel dumb I didn't realize it wasn't needed and copy/paste would just work. Sorry about that
