### ISSUE TITLE
[Feature Request] Adding Sponsorblock into the Browser Containers

### ISSUE THREAD

**Issue by ghost** [m1k1o/neko#83]
Adding Sponsorblock into the Browser Containers
https://sponsor.ajay.app

Would make watching YouTube videos 1000x better.

**Comment by m1k1o** [comment]
That can be customized: https://github.com/m1k1o/neko#want-to-customize-and-install-own-addons-set-custom-bookmarks

Would be interesting to add customization to https://github.com/m1k1o/neko-rooms/, where user can choose own room configuration in UI.

**Comment by m1k1o** [comment]
It is possible to customize the mountpoints for the policy file in neko-rooms already. Documentation is missing, but I wrote it in this issue: https://github.com/m1k1o/neko-rooms/issues/22#issuecomment-867897112

Yes, could be default. For now I am keeping the same addons as in upstream repo and want to focus on neko-rooms, where you can choose any addon you want. Not sure if upstream repo will be ever active, though.

**Comment by catSIXe** [comment]
Would be nice, could finally make that XnViewMP container ( to look trough pictures/videos ).

**Comment by m1k1o** [comment]
PR in progress: https://github.com/m1k1o/neko-rooms/pull/23

![image](https://user-images.githubusercontent.com/7534274/127216635-46b5cc46-4805-4950-9f9e-e531e5f2aebe.png)
![image](https://user-images.githubusercontent.com/7534274/127216648-eb36228a-96d6-406b-9f89-555defc7a710.png)

**Comment by RisedSky** [comment]
I agree to use by default the extension sponsorblock, it's very usefull 😀
