### ISSUE TITLE
[Question] How to use RTMP feature

### ISSUE THREAD

**Issue by GabrielSerealia** [m1k1o/neko#88]
I've been trying to look for documentation on it but was unable to figure it out. How do you use the RTMP broadcast feature for Neko?

**Comment by GabrielSerealia** [comment]
After messing around with it I found out you can put your key at the end of the URL

Example: rtmp://a.rtmp.youtube.com/live2/35b2-ubwj-k45e-2m8u-0w5f

**Comment by m1k1o** [comment]
Yes, that should be documented. I'll add it. Thanks.

**Comment by m1k1o** [comment]
Now it should be more user friendly: 
![image](https://user-images.githubusercontent.com/7534274/129482273-0e311425-d5b3-4bbf-9f01-2f980b722292.png)

**Comment by GabrielSerealia** [comment]
Thanks <3
