### ISSUE TITLE
[Feature Request] Mouse - implicit control gain

### ISSUE THREAD

**Issue by ruralty** [m1k1o/neko#99]
I'd be willing to support developing the ability to allow admin and user to share control of the mouse without clicking the control switching button.

It could be as simple as click a button to enable share control (implicit control gain).

When the mouse is not being pressed, the other user can take control.

**Comment by m1k1o** [comment]
We could have flag `NEKO_CONTROL_TYPE` that can contain one of following values:
- **request** - need to request control every time.
- **click** - on every click on the screen control will be given.
- **move** - on every mouse move on the screen control will be given.

While **request** type is the current implemented.

**Comment by m1k1o** [comment]
This functionality was implemented recently, as control lock.
![image](https://user-images.githubusercontent.com/7534274/142459377-cfed3f2b-59fc-45d5-bc8a-6adb331ba779.png)

It can disable control for users.

**Comment by ruralty** [comment]
Does this update on my deployed VM instance automatically?

How about the implicit control gain?  (control is switched when any user moves the mouse)?

Any update coming?   *_*

**Comment by m1k1o** [comment]
No, auto update was not yet implemented. It needs to be done manually in terminal. Pulling new images with `docker pull m1k1o/neko:chromium` and then recreating all rooms.

No updates yet, I was quite busy last week.
